Tooltips
sandboxnu/searchneu-v1 pull request #108
Opened 2021-04-13 23:58 UTC by amielmon

Added tooltips back. Here are screenshots:

![Screen Shot 2021-04-13 at 7 37 16 PM](https://user-images.githubusercontent.com/23239188/114635286-6646b400-9c92-11eb-8f27-c0182a8ed29e.png)

![Screen Shot 2021-04-13 at 7 40 54 PM](https://user-images.githubusercontent.com/23239188/114635303-71014900-9c92-11eb-8e44-a7462475a983.png)

![Screen Shot 2021-04-13 at 7 36 48 PM](https://user-images.githubusercontent.com/23239188/114635316-78285700-9c92-11eb-89b0-d248878808aa.png)

![Screen Shot 2021-04-13 at 7 36 16 PM](https://user-images.githubusercontent.com/23239188/114635321-7a8ab100-9c92-11eb-8361-641c044b9533.png)

![Screen Shot 2021-04-13 at 7 47 24 PM](https://user-images.githubusercontent.com/23239188/114635332-7e1e3800-9c92-11eb-9d0a-90bb0ef04df2.png)

2021-04-14 00:06 UTC, megandouli requested changes
Can you fix the failing typescript checks, front-end tests, and merge from master so you have the most recent changes? Not sure why the Vercel deployment is failing

2021-04-15 00:47 UTC, andrewydai commented on components/types.ts
> -  prettyUrl: string;
Just wondering what this change is for.

2021-04-15 00:47 UTC, andrewydai commented on pages/404.tsx
> +      <div className="four04-title-text">something&apos;s borked</div>
Good catch on the 404 page. I was reading online about this but it seems like ```&#39;``` is preferred. 
[https://stackoverflow.com/questions/419718/html-code-for-an-apostrophe](https://stackoverflow.com/questions/419718/html-code-for-an-apostrophe)
[http://www.madore.org/~david/computers/unicode/htmlent.html](http://www.madore.org/~david/computers/unicode/htmlent.html)
Let me know what you think

2021-04-15 01:06 UTC, megandouli approved these changes
very cool 👍

2021-04-15 01:09 UTC, amielmon commented on components/types.ts
> -  prettyUrl: string;
Oops added this back. I mistakenly thought that this field was no longer being returned from the backend because the globe links weren't working before (I think they broke sometime during the rewrite) but this must have been due to a typo.

2021-04-15 01:10 UTC, amielmon commented on pages/404.tsx
> +      <div className="four04-title-text">something&apos;s borked</div>
I'm used to using '&apos;' and similar since its more mnemonic but I'll use your suggestion since it has HTML 4 support.

2021-04-15 15:46 UTC, merged