Pull request templatee
sandboxnu/searchneu-v1 pull request #109
Opened 2021-04-14 02:04 UTC by andrewydai

# Purpose

###### A brief description of the purpose of the PR's changes for the project.
This PR adds a pull request template and a commit template to the docs of our projects. The PR template (when merged to master), will auto fill any pull request made for the project going forward. The commit template is a document to reference for our commit standards we agree on as a team.

# Tickets

###### A link to any tickets this PR is associated with on trello.

- No ticket

# Contributors

###### Anyone who contributede to this PR for future reference

- Andrew Dai

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

- Adds a ```pull_request_template.md``` to auto fill future pr's
- Adds a ```commit_template.md``` to reference for commit formats
-

# Checklist

- [x] Filled out PR template :wink:
- [x] Check delete source branch
- [x] Check squash commits
- [x] Passing linting checks
- [x] Documentation and comments in code
- [x] Test coverage for code
- [x] Commits are neatly ordered

<br>
@sandboxnu/searchneu

2021-04-15 07:34 UTC, dillonhammer requested changes

2021-04-15 07:34 UTC, dillonhammer commented on docs/commit_template.md
> +As a team, we are prefering to use `git rebase` over git `git merge`. The main reason is because a rebase reduces the frequency of "merge commits" that
```suggestion
As a team, we are preferring to use `git rebase` over `git merge`. The main reason is because a rebase reduces the frequency of "merge commits" that
```

2021-04-15 07:34 UTC, dillonhammer commented on docs/commit_template.md
> +Here are the 7 steps for a good git commit message, as per [Chris Beam's blog](https://guides.github.com/features/mastering-markdown/)
I believe the link is incorrect, unless Chris Beam's blog has really branched out

2021-04-15 07:34 UTC, dillonhammer commented on docs/commit_template.md
> +2. Checkout the branch you want to rebase
I think that phrasing it as "the branch you want to rebase" might still be a little confusing for someone who has never heard of rebasing before. Obv the linked blog should answer all questions, but for this example maybe it would help to give the (very common) use case of rebasing a feature branch onto the master branch.

2021-04-15 07:34 UTC, dillonhammer commented on docs/commit_template.md
> +3. run `git rebase [FIRST BRANCH NAME]`
Similar note here, I think that "FIRST BRANCH NAME" could be confusing.

2021-04-15 07:34 UTC, dillonhammer commented on docs/pull_request_template.md
> +###### Anyone who contributede to this PR for future reference
```suggestion
###### Anyone who contributed to this PR for future reference.
```

2021-04-15 07:34 UTC, dillonhammer commented on docs/pull_request_template.md
> +###### A link to any tickets this PR is associated with on trello.
```suggestion
###### A link to any tickets this PR is associated with on Trello.
```

2021-04-15 07:34 UTC, dillonhammer commented on docs/pull_request_template.md
> +- [ ] Commits are neatly ordered
I think this last checkbox is maybe too vague - neatness can be subjective, and I believe in our discussion we decided that we wouldn't be going as far as doing `git commit --amend` to cleanup commit history, so I don't think we are actually requiring commits to be re-ordered/cleaned up.

We did talk about cleaning up the *PR message*, so that might be something to note here. If that's what you were referring to in this item then I just think it could be re-worded so that it's clear we aren't editing the commits themselves.

2021-04-15 07:34 UTC, dillonhammer commented on docs/commit_template.md
> +   For more details, check [this Atlassian blog](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) out
I think one thing that could maybe be added to this doc is the rationale behind squashing PRs. I saw the line on the PR checklist, but I think it would be useful to just have a short explanation of *why* we decided to do that, so that readers know to keep PRs relatively small and edit the PR message to accurately reflect all the changes.

If PR squashing is added in, then I also think that this file encompasses more than just a commit template, and so maybe it could be renamed to something more general like `git_guide` or `git_practices`.

2021-04-15 23:22 UTC, andrewydai commented on docs/commit_template.md
> +As a team, we are prefering to use `git rebase` over git `git merge`. The main reason is because a rebase reduces the frequency of "merge commits" that
good catches 😢

2021-04-15 23:22 UTC, andrewydai commented on docs/commit_template.md
> +Here are the 7 steps for a good git commit message, as per [Chris Beam's blog](https://guides.github.com/features/mastering-markdown/)
Lol yeah I had the wrong thing on my clipboard tyty

2021-04-15 23:24 UTC, andrewydai commented on docs/pull_request_template.md
> +###### Anyone who contributede to this PR for future reference
Yeah...mb OK I swear my mac double types e's

2021-04-15 23:50 UTC, andrewydai commented on docs/pull_request_template.md
> +- [ ] Commits are neatly ordered
I'm just going to go ahead and delete that bullet point, since I the nature of the PR template is the PR message cleanliness. These bullet points are almost speculative as I wasn't sure what we would want here. But agreed, not reordering commits.

2021-04-15 23:52 UTC, andrewydai commented on docs/pull_request_template.md
> +- [ ] Commits are neatly ordered
Although maybe I'm confused. Is the comment the PR template provides on the PR going to be the final message for the squash (aka the squash commit). I am forgetting...

2021-04-16 00:00 UTC, dillonhammer commented on docs/git_practices.md
> +3. run `git rebase [FEATURE BRANCH NAME]`
I like the new example, should this be `git rebase master` though?

2021-04-17 20:16 UTC, dillonhammer approved these changes

2021-04-18 18:41 UTC, puneetjohal approved these changes

2021-04-19 19:51 UTC, merged