Class pages sections
sandboxnu/searchneu-v1 pull request #112
Opened 2021-04-20 00:39 UTC by megandouli

# Purpose

Wraps up the minimum required features for class pages. Completes the Section part and adds a `View more info` button from search results that links to class pages.

<br>

# Tickets

- [Trello (not much detail)](https://trello.com/c/JCFW5WGZ/168-class-pages-sections-display)
- [Figma Design](https://www.figma.com/file/Tcoudsnep7oWsphBXXmLvO/%F0%9F%86%95-New-Features?node-id=17%3A2)

# Contributors

- Megan Li
- Andrew Dai
- Puneet Johal
- Becca Johnson (Designs)

-

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

-
-
-

# Notes

For class pages to truly be done, still need:
1. Notification button on Section cards in class pages
2. Some message / indication if someone's trying to view a class page for a non-existent class
3. Some backend issues so there's some hacky stuff on the frontend for class pages but we should eventually fix the backend and remove the frontend hack
4. Mobile designs
5. Tests

<br>

# Checklist

- [x] Filled out PR template :wink:
- [x] Is passing linting checks
- [x] Is passing tsc
- [x] Is passing existing tests (front-end tests)
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2021-04-20 01:10 UTC, megandouli commented on pages/[campus]/[termId]/classPage/[subject]/[classId].tsx
> +      Router.push('/404');
why can't we just use `router` defined on line 17?

2021-04-20 01:44 UTC, puneetjohal requested changes

2021-04-20 01:44 UTC, puneetjohal commented on components/ClassPage/ClassPageReqsBody.tsx
> +import { Requisite } from '../types';
This import is unused
```suggestion
```

2021-04-20 01:44 UTC, puneetjohal commented on components/ClassPage/ClassPageSections.tsx
> +function splitMeetingsAndExamTimes(meetings) {
Bumping the github lint warning: there's no return type on this function

2021-04-20 01:44 UTC, puneetjohal commented on pages/[campus]/[termId]/classPage/[subject]/[classId].tsx
> +        <h3 style={{ margin: '20px' }}>Mobile designs coming soon!</h3>
Maybe let's word this like `Class pages coming to mobile soon!` (since the designs are more for us)

2021-04-20 01:47 UTC, puneetjohal commented on components/ResultsPage/Results/useSectionPanelDetail.tsx
> +  seatsRemaining: number,
We can delete the `Sections` import from the top of this file since it's now unused because of these changes.

2021-04-20 17:09 UTC, bugsalexander reviewed
I send more of my thoughts to you directly @megandouli but the TL;DR is that I think this is fine as is :)

2021-04-20 17:09 UTC, ghost commented on components/ClassPage/ClassPageSections.tsx
> +type ClassPageSection = { __typename?: 'Section' } & Pick<
Yes there is! This definition is equivalent to the following:

```typescript
type ClassPageSection = GetClassPageInfoQuery['class']['allOccurrences'][number]['sections'][number];
```

Basically, you can grab the specific type of a property (Even nested properties!) in Typescript. Checkout this link in the documentation: https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html

2021-04-20 17:09 UTC, bugsalexander commented on components/ClassPage/ClassPageSections.tsx
> +  }, [currTermIndex, selectedCampus, classPageInfo]);
This looks good to me!

2021-04-21 00:12 UTC, megandouli commented on components/ClassPage/ClassPageSections.tsx
> +type ClassPageSection = { __typename?: 'Section' } & Pick<
wait that's actually so helpful THANK YOU!!

2021-04-21 17:27 UTC, puneetjohal approved these changes

2021-04-21 22:07 UTC, merged