Ad refactor banner alerts
sandboxnu/searchneu-v1 pull request #117
Opened 2021-08-11 16:19 UTC by andrewydai

# Purpose

###### A brief description of the purpose of the PR's changes for the project.
This pr refactors the AlertBanner component to draw data from a yaml file in the public folder. This is to reduce the need to do inline code changes to add banners. Going forward, front page alert banners can be added by modifying the `alert-banners.yml` file.

<br>

# Tickets

###### A link to any tickets this PR is associated with on Trello.

- My bad, no ticket :( 

# Contributors

###### Anyone who contributed to this PR for future reference.

- Andrew Dai

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

- Adds the ability to load and use yaml files throughout the project
- Adds a yaml file for easier adding and changing of banners in the future
- alert-banners.yml supports modifying alert level, text, visibility, and links for alerts
- Can easily render multiple alerts now

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [x] Has documentation and comments in code
- [ ] Has test coverage for code
- [x] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2021-08-17 23:15 UTC, megandouli requested changes

2021-08-17 23:15 UTC, megandouli commented on components/common/AlertBanner.tsx
> +            <div className={`alertBanner ${alertBanner.alertLevel}Banner`}>
make sure you add a `key` prop to the `div` since you're mapping

2021-08-17 23:15 UTC, megandouli commented on package-lock.json
> +  "name": "searchneu-nextjs",
we shouldn't have both `package-lock.json` and `yarn-lock`. It looks like you installed dependencies using `npm install` which is what generated the `package-lock.json`. You should delete this file and reinstall the dependnecies using `yarn install`

2021-08-17 23:15 UTC, megandouli commented on components/common/AlertBanner.tsx
> +    setValue(value + 1);
I'm kinda confused about the design here. To me, it'd make more sense if the `AlertBanner` component renders 1 banner, so instead of mapping over all the banner data here, do it in `pages/[campus]/[termId].tsx` where you're actually rendering all the banners. 

I also don't understand why `value` is in state besides forcing a re-render when the user closes the banner. In that case, it seems like `isVisible` is what should actually be on state (default it to `props.isVisible`).

2021-08-18 23:47 UTC, andrewydai commented on components/common/AlertBanner.tsx
> +            <div className={`alertBanner ${alertBanner.alertLevel}Banner`}>
good catch, done

2021-08-18 23:47 UTC, andrewydai commented on package-lock.json
> +  "name": "searchneu-nextjs",
changed

2021-08-18 23:48 UTC, andrewydai commented on components/common/AlertBanner.tsx
> +    setValue(value + 1);
changed

2021-08-18 23:59 UTC, megandouli approved these changes
awesome!

2021-08-20 00:24 UTC, merged