Twilio
sandboxnu/searchneu-v1 pull request #120
Opened 2021-08-27 03:31 UTC by dillonhammer

# Purpose

Rework notifications to use Twilio

<br>

# Tickets

https://trello.com/c/CxbutQVM/209-move-our-notification-system-away-from-facebook-notifications-to-twilio

# Contributors

@dillonhammer 
@megandouli 

# Feature List

- Add a Phone # verification modal when a user clicks to sign up for notifications
- Refactor existing notification toggles to send requests to new backend endpoint
- Remove all Facebook-related code

# Notes

Overall notification flow in `docs/Notifications.md`
New environment vars:
`NEXT_PUBLIC_NOTIFS_ENDPOINT`

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [x] Is passing linting checks
- [x] Is passing tsc
- [x] Is passing existing tests
- [x] Has documentation and comments in code
- [ ] Has test coverage for code
- [x] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2021-09-23 02:29 UTC, andrewydai requested changes

2021-09-23 02:29 UTC, andrewydai commented on package.json
> +    "antd": "^4.16.9",
Can we use semantic-ui for out of the box stuff like buttons? It's already in the project and I think we should avoid adding external libraries if they're redundant. Alternatively, is there a specific reason we chose to use antd components for this pr? This comment is for all the spots that use antd

2021-09-23 02:29 UTC, andrewydai commented on components/Header.tsx
> +export interface UserInfo {
can we move this to `types.ts` for consistency? I feel it was a common issue in the past for types to live in odd files and would be difficult to find. If there's no reason, I'd like to move it to `types.ts`

2021-09-23 02:29 UTC, andrewydai commented on components/PhoneModal.tsx
> +export function PhoneModal({
I notice a lot of functions, useStates, and general bulkiness to this component. I think it would be beneficial to  either make it a class component (and with state and methods on the class), or make it have a service file of some sort to increase readability

2021-09-23 02:29 UTC, andrewydai commented on components/PhoneModal.tsx
> +      .catch((error) => {
Also think we should fix all the linting warnings in this file

2021-09-23 02:29 UTC, andrewydai commented on components/PhoneModal.tsx
> +  const onCountryCodeChange = (value: any): void => {
Could maybe consolidate some of these validator functions into one number validator function that takes an argument, a function (state setter), and maybe a regex (but that doesn't look necessary right now).

2021-09-23 02:29 UTC, andrewydai commented on components/PhoneModal.tsx
> +      .catch((error) => {
For the event.target.value typing which is being used as `any` in this file, can maybe use something like `HTMLInputElement`. Unsure if this works though, have to test a little

2021-09-23 02:29 UTC, andrewydai commented on components/PhoneModal.tsx
> +      .post(`${process.env.NEXT_PUBLIC_NOTIFS_ENDPOINT}/sms/signup`, {
Might be nice to have some additional regex validation here so we don't need to send a request to the backend to know we have an issue. Thoughts?

2021-09-23 02:29 UTC, andrewydai commented on components/PhoneModal.tsx
> +    if (!isNaN(value) && reg.test(value)) {
I think this is redundant. Aren't these regex's only verifying each character is a numeric value (which isNaN does too)? I think it'd be good to have a regex that allows for `()` and `-` since those are common

2021-09-23 02:29 UTC, andrewydai commented on components/ResultsPage/Results/NotifSignUpButton.tsx
> +export default function NotifSignUpButton({
I think this button is maybe too simple to be a component. It basically provides users a button that they can only control the `onClick` prop for and has unchangeable text. I think it's probably fine to just make this one line inline element in the `SignUpForNotifications.tsx`

2021-09-23 02:29 UTC, andrewydai commented on pages/[campus]/[termId]/search/[query].tsx
> +              userInfo={userInfo}
I am a little concerned about the passing of all these props down the massive component tree. The 2 reasons I am worried are:
1. This bloats code, as every intermediary component between this component and the SignUpForNotifications component has to add these to their props list and their props interfaces
2. This could cause problems in performance as changes on this data can cause a ripple of rerenders on our state tree when we really only want to rerender parts of it.
In terms of solutions, I would reference this [React context](https://reactjs.org/docs/context.html#when-to-use-context). React context are a bit involved and maybe too heavy handed here, composition might be the way to go. Essentially, in composition we would pass down the SignUpForNotifications component from the top to where it's needed (inversion of control). 

It might not be the right thing to do here, LMK what you think I'm open to suggestions.

2021-09-23 02:29 UTC, andrewydai commented on docs/Notifications.md
> +TODO: @Megan
Is this still a TODO or does this refer to the prod setup of our twilio endpoints? I thought the backend code was done for texting

2021-10-04 20:47 UTC, megandouli reviewed
leaving a comment so I don't forget, we should remove the FB alert and add a new one about SMS notifications

2021-10-06 01:05 UTC, megandouli commented on docs/Notifications.md
> +TODO: @Megan
yeah the backend code isn't totally done, just have the minimal stuff out. I'll create a ticket for these things.

2021-10-06 01:10 UTC, megandouli commented on components/PhoneModal.tsx
> +export function PhoneModal({
hmm there is a good amount of state on this component but I didn't find it very hard to read or understand, and splitting it up might just make it harder to figure out how pieces are connected so I'm leaning towards not breaking this component up.

2021-10-06 01:11 UTC, megandouli commented on components/PhoneModal.tsx
> +      .catch((error) => {
I think we can use `string` for `target.value` instead of `any`.

2021-10-06 01:24 UTC, megandouli commented on components/PhoneModal.tsx
> +    if (!isNaN(value) && reg.test(value)) {
country codes should only ever by numbers so I think this regex check is fine... however, it's true that valid phone numbers _could_ have `()` and `-` so I think we're going to remove the regex check in `onPhoneChange` and basically allow them to put in whatever, then perform a regex check before submitting the phone number to the backend, stripping out the extra valid characters.

2021-10-06 01:25 UTC, megandouli commented on components/PhoneModal.tsx
> +      .post(`${process.env.NEXT_PUBLIC_NOTIFS_ENDPOINT}/sms/signup`, {
yee

2021-10-06 01:36 UTC, megandouli commented on components/ResultsPage/Results/NotifSignUpButton.tsx
> +export default function NotifSignUpButton({
true, it is a very simple component right now but I can imagine it getting a little more complicated when we implement Diana's designs, so I'd prefer to leave it as it is.

2021-10-07 04:51 UTC, kiminkim724 commented
I changed onPhoneNumberSubmit so that the code automatically adds the dashes for the phone number as they input each number. So the users are only allowed to input numbers, which means that the only cases that would return an invalid phone number would be when the phone number isn't long enough or it's an invalid phone number. I was wondering if I should create a separate function to check for the phone number length or just have an if statement at the top of onPhoneNumberSubmit to check for this?

2021-10-10 19:26 UTC, andrewydai requested changes
Overall, the changes implemented are good, but the logic around the phone is iffy to me, and there's some syntax/convention issues that should be cleaned up. LMK if you have questions!

2021-10-10 19:26 UTC, andrewydai commented on components/PhoneModal.tsx
> +    console.log(`Phone number: ${value}`);
Remove

2021-10-10 19:26 UTC, andrewydai commented on components/PhoneModal.tsx
> +    const reg = /^[\d-]*$/;
Maybe we should move all these regex's outside of the component to a constant at the top of this file. Some are reused, but also redeclaring them every function call seems akin to doing `new RegExp()` everytime as per this [post](https://stackoverflow.com/questions/9750338/dynamic-vs-inline-regexp-performance-in-javascript/32523333) which could be expensive

2021-10-10 19:26 UTC, andrewydai commented on components/PhoneModal.tsx
> +      value == '' ||
Always use triple equals with JS/TS. Double equals is strange, and will return true for things like `1 == "1"`. I'm honestly surprised we don't have a linter to yell at this lol

2021-10-10 19:26 UTC, andrewydai commented on components/PhoneModal.tsx
> +      (!isNaN(parseInt(value)) &&
NaN is falsy, meaning in a boolean expression it is false. In this case, parseInt() will give NaN if it is not a number, so you don't need isNaN.

2021-10-10 19:26 UTC, andrewydai commented on components/PhoneModal.tsx
> +      (!isNaN(parseInt(value)) &&
Actually, this may give 0 itself which is falsy, so maybe keep this.

2021-10-10 19:26 UTC, andrewydai commented on components/PhoneModal.tsx
> +  function checkPhoneNumberDashes(value: string): boolean {
Let's try to keep style in the same, especially because this is already in a function body, aka `const functionName = () =>`. Also, I prefer predicate functions be named as a function, `isPhoneNumberDashesValid` for example.

2021-10-10 19:26 UTC, andrewydai commented on components/PhoneModal.tsx
> +      if (value == '') {
Isn't this redundant?

2021-10-10 19:26 UTC, andrewydai commented on components/PhoneModal.tsx
> +      } else {
Can replace with `else if() {` on same line

2021-10-10 19:26 UTC, andrewydai commented on components/PhoneModal.tsx
> +  function checkPhoneNumberDashes(value: string): boolean {
Also, unsure if this is necessary given the invariant restriction above and that users can enter dashes. At least from what i understand, let me know

2021-10-10 19:26 UTC, andrewydai commented on components/PhoneModal.tsx
> +      console.log(value.length);
remove

2021-10-10 19:26 UTC, andrewydai commented on components/PhoneModal.tsx
> +      value.length == 12 ? setResendDisabled(false) : setResendDisabled(true);
In general with this function, i'm a little lost what the logic flow is. Maybe some comments or walk through would help me.

2021-10-12 17:13 UTC, kiminkim724 commented on components/PhoneModal.tsx
> +      (!isNaN(parseInt(value)) &&
I think the regex check should already check if it's a digit, so honestly, I think the whole isNaN check might be redundant? Any thoughts on that?

2021-10-12 17:14 UTC, kiminkim724 commented on components/PhoneModal.tsx
> +  function checkPhoneNumberDashes(value: string): boolean {
I got rid of the function, I found a better way to implement the dashes in the phone number.

2021-10-12 17:15 UTC, kiminkim724 commented on components/PhoneModal.tsx
> +      if (value == '') {
I realized the problem was when I was calling the regexp to add dashes in the phone number wouldn't work when the length is zero, so I just checked if the length was greater than zero in the statement below.

2021-10-12 17:16 UTC, kiminkim724 commented on components/PhoneModal.tsx
> +      value.length == 12 ? setResendDisabled(false) : setResendDisabled(true);
I've cleaned up the code so it's a lot simpler, I'll try to leave some comments to explain what some of the parts do.

2021-10-12 18:46 UTC, andrewydai commented on components/PhoneModal.tsx
> +  const phoneReg = /^\d*$/;
sorry this is nitpicky, let's do this outside the PhoneModal function but not with the imports, just before this function. And use all caps to signify a constant.

2021-10-14 18:33 UTC, andrewydai approved these changes

2021-10-15 05:56 UTC, merged