Add total aggregation value in filter headers
sandboxnu/searchneu-v1 pull request #125
Opened 2021-10-07 22:15 UTC by puneetjohal

# Purpose

Add total aggregation value in filter headers to improve user understanding of how many results are being displayed.

<br>

# Tickets

https://trello.com/c/65DClxKh

# Contributors

- @puneetjohal 

# Notes

Here's a screenshot showing the expected behavior:

![image](https://user-images.githubusercontent.com/33487680/136469209-a6e89835-65cf-458a-b87d-56f14087120b.png)

<br>

# Checklist

- [x] Filled out PR template :wink:
- [x] Approved by designers
- [x] Is passing linting checks
- [x] Is passing tsc
- [ ] Is passing existing tests
- [ ] ~~Has documentation and comments in code~~
- [ ] ~~Has test coverage for code~~
- [x] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2021-10-09 21:06 UTC, megandouli requested changes
I don't think this behavior makes sense... I select the `CS` subject filter which has 69 results, so I'd expect the aggregation value to be 69 instead of 1478. @beccajohnson17 what do you think?

<img width="271" alt="Screen Shot 2021-10-09 at 5 04 18 PM" src="https://user-images.githubusercontent.com/55663526/136673786-099378b0-f1de-4001-8702-cedd0f259b40.png">

2021-11-13 00:15 UTC, beccajohnson17 commented
I agree with @megandouli that once a filter is chosen, then the header should update to show the running total of all filters selected. So it would say 69, but if EECE was added, it would be 114. Also a side question but wouldn't the Class Type also have a running total?

2022-02-06 20:53 UTC, puneetjohal commented
Waiting on designer input for this one.

2022-02-06 21:31 UTC, megandouli approved these changes
looks good! just 2 super minor things

2022-02-06 21:31 UTC, megandouli commented on utils/filterUtils.ts
> +export function getTotalAggregation(selected, options): string {
nit: I think it makes more sense for this function to return a number instead of a formatted string. The name implies it returns a total so it shouldn't also be concerned with string formatting

2022-02-06 21:31 UTC, megandouli commented on utils/filterUtils.ts
> +    let selectedOptions = options.filter((option) =>
just make this a const to remove the lint error

2022-02-06 21:48 UTC, puneetjohal commented
We're ditching this design, I'll put in a new PR for the new design.

2022-02-06 21:48 UTC, closed without merging