Remove hardcoded term IDs
sandboxnu/searchneu-v1 pull request #134
Opened 2021-11-07 21:42 UTC by hankewyczz

# Purpose

###### Remove hardcoded term IDs - get them programmatically from the backend

<br>

# Tickets

###### https://trello.com/c/xRH6xepp/216-remove-hardcoded-termids

-

# Contributors

###### Zachar Hankewycz, Kimin Kim

-

# Feature List

###### Adds support for asyncronously fetching the term IDs from the backend (and updating the list asyncronously across all components

-
-
-

# Notes

###### N/A

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ x] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2021-11-08 18:57 UTC, andrewydai requested changes
General comment: I recognize that the whole system of components depending on hardcoded termids was difficult to change but something doesn't fully sit well with the useEffect useState pattern I'm seeing everywhere. Wonder if a smarter way to do this is on the whole app container (_app) we wait for it to mount, and then immediately request for every termid we can. When that finishes, we set a global readable state on react context that everyone can update off of when it changes, and show the correct values. Meanwhile everywhere else displays empty values until that comes in. 

Looking for other devs thoughts too on this

2021-11-08 18:57 UTC, andrewydai commented on components/Header.tsx
> +          link: termAndCampusToURLCallback(terminfo.value, campus),
To fix the linting issue pointing here, you need to move the `termAndCampusToURLCallback` definition above these two useEffect hooks

2021-11-08 18:57 UTC, andrewydai commented on components/HomePage/ExploratorySearchButton.tsx
> +import SectionsTermNav from '../ClassPage/SectionsTermNav';
remove

2021-11-08 18:57 UTC, andrewydai commented on components/HomePage/HomeSearch.tsx
> +    Promise.all(campusLinksTemp).then((data) =>
remove arg from lambda callback

2021-11-08 18:57 UTC, andrewydai commented on components/ResultsPage/SearchDropdown.tsx
> +import React, { ReactElement, useState } from 'react';
remove useState

2021-11-09 03:34 UTC, megandouli requested changes
overall agree with Andrew; all the `useStates` and `useEffects` don't seem appropriate since really we just want to make 1 request to the backend to fetch termIds. I'm not a React expert, so I can't say what the right way to do this is... would encourage you to ask in #engineering-support in Slack

2021-11-09 03:34 UTC, megandouli commented on components/Header.tsx
> +
would prefer to move these `useState`s towards the top of the component so someone looking at the code can see what state the component has immediately

2021-11-09 03:34 UTC, megandouli commented on components/HomePage/HomeSearch.tsx
> +  Object.values(Campus).map((c) => (emptyLinks[c] = ''));
better style to create an obj with keys from an array would be to use `.reduce` instead of `.map` so something like 

```
const emptyLinks = Object.values(Campus).reduce((acc, curr) => {...body function}, {});
```

2021-11-09 03:34 UTC, megandouli commented on components/global.ts
> +    .then((res) => res['termInfos']);
I don't think you need to do `await` and `.then()` here, you should be able to just do 

```
const data = (await gqlClient
    .getTermIDsByCollege({ subCollege: subCollege })).termInfos;
``

2021-11-09 03:34 UTC, megandouli commented on components/global.ts
> +// TODO - Decide how often we should force-rescrape (Otherwise, we won't re-hit the backend until the next time the program is resarted.)
I wouldn't call this `force-rescrape`... it'd be confusing since the backend has scrapers. Really, this is about refetching data from the backend. Why not just let each frontend client make the request once per campus? Instead of keeping a cache in memory, you could memoize `getTermInfoFromBackend` using `memoize` from `lodash` and use the campus as the cache key. Also maybe rename `getTermInfoFromBackend` to `fetchTermInfo`

2021-11-09 03:34 UTC, megandouli commented on components/HomePage/ExploratorySearchButton.tsx
> +      if (typeof t !== 'undefined') {
why are we checking the typeof t isn't undefined instead of the value of t? Also when would `t` be undefined?

2021-11-09 03:34 UTC, megandouli commented on components/HomePage/HomeSearch.tsx
> +        .then((url) => (campusLinksDict[c] = url))
this doesn't need to be 2 `.then()`s; you can convert the `term` to `url` in one function body

2021-11-09 03:34 UTC, megandouli commented on components/HomePage/HomeSearch.tsx
> +      .then((data) => setTermInfos(data));
don't need 2 `.then()`s, conversion from `data` to list of `termInfos` can happen in one `.then`

2021-11-09 03:34 UTC, megandouli commented on components/Header.tsx
> +      .then((data) => setTermInfos(data));
pretty sure you can do all this inside one `then` see below for similar comments

2021-11-09 03:34 UTC, megandouli commented on components/HomePage/HomeSearch.tsx
> +    // This pattern isn't intuitive, but Promise.all can't resolve on a dictionary object, so we have to work around that
there's gotta be a better way to do this but I'm too tired to think of it

2021-11-09 03:34 UTC, megandouli commented on components/global.ts
> +async function getTermInfoFromBackend(c: Campus): Promise<TermInfo[]> {
I'd probably rename this file to `terms.ts` at this point

2021-11-09 03:34 UTC, megandouli commented on pages/api/sitemap.xml.ts
> +  let latestTerms: [Campus, string][];
you can use `p-map` (there are more examples of its usage in course-catalog-api) if you're mapping over something and the mapper function is async. Alternatively since the `.map` returns a Promise, you can `Promise.all` a `.map`

2021-11-14 23:17 UTC, megandouli approved these changes
just small things to fix; fantastic job!!!

2021-11-14 23:17 UTC, megandouli commented on components/terms.ts
> +export async function fetchTermInfo(): Promise<{ [key: string]: TermInfo[] }> {
minor Typescript thing, instead of `{[key: string]: TermInfo[]}` to represent an object where the key is a string and the value is a list of TermInfos, use `Record<string, TermInfo[]>`. If you can be more specific with your key, that'd be even better. In this case, I think it'd be `Record<Campus, TermInfo[]>`.

Note that `Record<Campus, TermInfo[]>` means this type needs to have every key in `Campus`. If that's not the case, you can use `Partial<Record<Campus, TermInfo[]>>` which means the type does not need every key in `Campus` but if it does have a key, the key is a `Campus`.

2021-11-14 23:17 UTC, megandouli commented on pages/[campus]/[termId].tsx
> +              )}
unless `termInfos[campus]` could be undefined, these two blocks can be combined into a ternary so something like

```
{ termInfos[campus].length === 0 ? <LoadingContainer />  : <HomeSearch termId={termId} campus={campus} /> }
```

2021-11-14 23:17 UTC, megandouli commented on utils/TermInfoProvider.tsx
> +const emptyTermInfos: { [key: string]: TermInfo[] } = Object.values(
use the type from my other comment here

2021-11-17 00:30 UTC, andrewydai requested changes
Great work! There are a few linting warnings that should be addressed, and I also think it could be nice to export a function on the TermInfoProvider that does `return useContext(termsContext)` so you don't have to import useContext and termsContext everywhere.

2021-11-19 02:22 UTC, NEUDitao approved these changes

2021-11-19 02:23 UTC, merged