Fix 'undefined undefined' for course page prereqs
sandboxnu/searchneu-v1 pull request #145
Opened 2021-12-03 20:10 UTC by hankewyczz

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

<br>

 On class pages, text-based (as opposed to courses) prereqs show up as undefined undefined. This is not an issue with search results.

# Tickets

###### A link to any tickets this PR is associated with on Trello.

-https://trello.com/c/4O0h9Cih/280-graduation-admission-dissertation-check-show-up-as-undefined-undefined-on-class-pages

# Contributors

###### Anyone who contributed to this PR for future reference.

-Zachar

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

Before:
![image](https://user-images.githubusercontent.com/27775244/144666565-f77ae08c-5eba-4fb9-b41a-3b6c903e88e6.png)

After:
![image](https://user-images.githubusercontent.com/27775244/144666589-cfa9d86d-8677-466c-a17c-c439ceda4368.png)

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2021-12-03 21:48 UTC, kiminkim724 approved these changes
Looks good!

2021-12-03 21:54 UTC, kiminkim724 requested changes

2021-12-03 21:54 UTC, kiminkim724 commented on components/ClassPage/PrereqsDisplay.tsx
> +  } else {
Actually on second thought, you check if prereqs is a string in an else if statement in useResultDetail.tsx. Do you want to do the same thing here? 
else if (typeof prereqs === 'string') instead of just else?

2021-12-05 00:00 UTC, megandouli commented on components/ClassPage/PrereqsDisplay.tsx
> +  } else {
@kiminkim724 that shouldn't be necessary if we're not doing type casting (which is what line 74 used to be). TypeScript is smart enough to infer types based off control flow so the type of `prereq` is a `Requisite` which is a union of `CompositeReq`, `CourseReq`, and `string`. If we reach the else case, TypeScript will know it's a string so it should be safe. If the type of `Requisite` ever changes, TypeScript will probably complain

2021-12-05 00:01 UTC, megandouli approved these changes
:yay:

2021-12-05 21:05 UTC, merged