Mobile class pages part 1
sandboxnu/searchneu-v1 pull request #155
Opened 2022-03-03 13:56 UTC by puneetjohal

# Purpose

###### A brief description of the purpose of the PR's changes for the project.
The first part of the mobile class page epic.

<br>

# Tickets

###### A link to any tickets this PR is associated with on Trello.\

- https://trello.com/c/BibeeNlf/295-mobile-class-pages-part-1

# Contributors

###### Anyone who contributed to this PR for future reference.

- @puneetjohal 
- @andrewydai 

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

![image](https://user-images.githubusercontent.com/33487680/156578361-236cfe33-8176-4849-8692-ae5cd49c1cd3.png)
![image](https://user-images.githubusercontent.com/33487680/156578461-92831541-9115-47e9-a6af-001d84e5805c.png)

# Notes

- The expandables with more info (i.e. recent professors, recent semesters offered) are currently empty
- The notification button doesn't do anything

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-03-06 01:12 UTC, hankewyczz requested changes
Looks good! 

Besides the comments I left, I have one issue - the grad/undergrad classification.

Take CS5800 (grad Algo) - it shows as [undergraduate](https://searchneu-95yuw09wj-sandboxneu.vercel.app/NEU/202230/classPage/CS/5800). However, on Banner, the course says that "Must be enrolled in one of the following Classifications: Graduate"

We don't have a good way of knowing this is a grad course from our API, so the best thing might just be to change the phrasing (instead of saying "Course Level", maybe just list the college?)

2022-03-06 01:12 UTC, hankewyczz commented on components/ClassPage/mobile/MobileClassInfoExpandable.tsx
> +  classPageInfo,
This argument doesn't seem to be used?

2022-03-06 01:12 UTC, hankewyczz commented on components/ClassPage/mobile/MobileClassInfoExpandable.tsx
> +        }
```suggestion
        className={"mobileClassInfoExpandable__header" + (expanded ? "--expanded" : "")}
```

2022-03-06 01:12 UTC, hankewyczz commented on components/ClassPage/mobile/MobilePageContent.tsx
> +                {showMore ? 'Show less' : 'Show more'}
This seems a little confusingly named - (if `showMore` is true, doesn't it seem like 'Show more' should be returned?). Maybe `showingMore` would be more explicit

2022-03-06 01:12 UTC, hankewyczz commented on components/ClassPage/mobile/MobilePageContent.tsx
> +                <p>In this course, there is, on average:</p>
```suggestion
                <p>In this course, there are, on average:</p>
```

2022-03-06 01:12 UTC, hankewyczz commented on components/ClassPage/mobile/MobilePageContent.tsx
> +                      %
If you want this to be a percent, multiply by 100 - right now it's just a decimal 

example:
![image](https://user-images.githubusercontent.com/27775244/156904858-2a135f3f-3e2f-4f81-9892-3911a0168893.png)

2022-03-06 17:47 UTC, puneetjohal commented on components/ClassPage/mobile/MobileClassInfoExpandable.tsx
> +  classPageInfo,
it will be in the next iteration!

2022-03-06 21:07 UTC, puneetjohal commented
> Looks good!
> 
> Besides the comments I left, I have one issue - the grad/undergrad classification.
> 
> Take CS5800 (grad Algo) - it shows as [undergraduate](https://searchneu-95yuw09wj-sandboxneu.vercel.app/NEU/202230/classPage/CS/5800). However, on Banner, the course says that "Must be enrolled in one of the following Classifications: Graduate"
> 
> We don't have a good way of knowing this is a grad course from our API, so the best thing might just be to change the phrasing (instead of saying "Course Level", maybe just list the college?)

The course level thing is a vestige of the desktop class pages, but I agree with this feedback. @andrewydai thoughts on changing course level to college on both the mobile and desktop class pages?

2022-04-03 18:39 UTC, hankewyczz approved these changes
🚀  looks good to me

2022-04-03 18:41 UTC, merged