Notifications Design (Desktop)
sandboxnu/searchneu-v1 pull request #157
Opened 2022-03-08 00:17 UTC by koulopoulos

# Purpose

* Implements the Twilio SMS notification registration flow designs for desktop.

# Tickets

- [Trello - Notifications Design (Desktop)](https://trello.com/c/fQZvYH2K/300-notifications-design-desktop)

# Contributors

- @koulopoulos

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

- Add new `Modal` component and refactor `PhoneModal` to avoid dependency on [antd](https://www.npmjs.com/package/antd)
- Delegate modal registration step views to individual components
- Add [react-phone-number-input](https://www.npmjs.com/package/react-phone-number-input) to handle phone number input and country prefixes
- Add `notifications` directory

<img width="1440" alt="sms-button" src="https://user-images.githubusercontent.com/40676764/157137704-bb03efac-351a-4b65-8928-f11cbe5ae5fb.png">
<img width="1440" alt="modal-phone-number" src="https://user-images.githubusercontent.com/40676764/157137738-f1dfd429-7a07-460b-93f1-61d5708511c5.png">
<img width="1440" alt="modal-phone-number--input" src="https://user-images.githubusercontent.com/40676764/157137730-242839f2-8636-4d10-bd79-2fb4c6e8e3a7.png">
<img width="1440" alt="modal-phone-number--invalid" src="https://user-images.githubusercontent.com/40676764/157137732-37fa559c-9bc4-4c51-ba96-282bad8b7ee9.png">
<img width="1440" alt="modal-phone-number--select" src="https://user-images.githubusercontent.com/40676764/157137736-2b7d47c3-7345-4b05-8c9a-a884d578d658.png">

# Notes

* Should discuss behavior of "User Menu" (display onHover vs onClick)

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [x] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-03-08 02:15 UTC, hankewyczz requested changes
Looking good! Just a small tweak or two and you're good to ship

2022-03-08 02:15 UTC, hankewyczz commented on styles/_PhoneModal.scss
> +    .PhoneInputCountrySelectArrow {
![image](https://user-images.githubusercontent.com/27775244/157151830-a7ccecc8-7617-4057-8a71-4b60a0085cb4.png)

I don't see the arrow on staging

2022-03-08 02:15 UTC, hankewyczz commented on components/Modal.tsx
> +      }
```suggestion
      if (event.key === 'Escape') {
          onCancel();
      }
```

Is there a reason for using a switch statement here?

2022-03-08 02:15 UTC, hankewyczz commented on __mocks__/style.js
> +module.exports = {};
[nit] Could you please add some info about what this file is and why we need it?

(Like https://github.com/sandboxnu/course-catalog-api/blob/master/babel.config.js)

2022-03-09 17:19 UTC, andrewydai requested changes
LGTM! The components look clean, and i've mostly left comments about some small things

2022-03-09 17:19 UTC, andrewydai commented on components/Modal.tsx
> +  props: React.PropsWithChildren<Props>
small thing, we usually destructure props in the function header, so like `export default function Modal({visible, onCancel, children}: ModalProps) {....}` and i think it'd be good to keep in that style

2022-03-09 17:19 UTC, andrewydai commented on components/Modal.tsx
> +interface Props {
nit, want to name this slightly more explicitly like ModalProps

2022-03-09 17:19 UTC, andrewydai commented on components/Modal.tsx
> +      }
agree with this

2022-03-09 17:19 UTC, andrewydai commented on components/ResultsPage/Results/NotifSignUpSwitch.tsx
> +    /*<Button className="tester" onClick={onClickWithAmplitudeHook}>
should this be here?

2022-03-09 17:19 UTC, andrewydai commented on components/notifications/modal/PhoneNumber.tsx
> +  props: PhoneInputStepProps
same thing as above with the props

2022-03-09 17:19 UTC, andrewydai commented on components/notifications/modal/PhoneNumber.tsx
> +import PhoneInput from 'react-phone-number-input';
nit (Sorry for all the nit stuff) put imports from packages before any local modules

2022-03-09 17:19 UTC, andrewydai commented on components/notifications/modal/SignUpModal.tsx
> +enum Status {
would like a slightly more clear comment about this enum, mainly the difference between `pending` and `loading`. Pending doesn't seem to be used anywhere other than an initial state (so maybe name change could be good)

2022-03-09 17:19 UTC, andrewydai commented on components/notifications/modal/SignUpModal.tsx
> +import { MoonLoader } from 'react-spinners';
same spiel with `PhoneNumber`'s imports

2022-03-09 17:19 UTC, andrewydai commented on components/notifications/modal/SignUpModal.tsx
> +    const onVerificationCodeSubmit = (): void => {
can we move this out of `useEffect`? I'm not sure if it's actually expensive in any way but feels wrong to constantly reinstantiate this function when the `useEffect`'s purpose is to just check if verification code changes to the full length and to auto send the request.

2022-03-09 17:19 UTC, andrewydai commented on components/notifications/modal/SignUpModal.tsx
> +  }, [verificationCode, onSignIn, onSuccess, phoneNumber]);
i'm not sure i'm fully following why `onSignIn, onSuccess and phoneNumber` are here, shouldn't this only be triggering when verification code is changing? I may be missing something

2022-03-09 17:19 UTC, andrewydai commented on components/notifications/modal/SignUpModal.tsx
> +enum Status {
on further reading of the code too i'm not sure about the full value of using status here. It doesn't seem to be read any place besides checking whether it's loading or not. It may be a little overkill to have an enum of states when the only state that matters for rendering is loading or not loading. Lmk your thoughts tho just my opinion

2022-03-09 17:19 UTC, andrewydai commented on components/notifications/modal/PhoneNumber.tsx
> +        <PhoneInput
nit: this component I would like the text to be stylized to be just a tad more transparent/gray it's little dark on the ui and made me think there was already text there

2022-03-09 17:19 UTC, andrewydai commented on components/notifications/modal/VerificationCode.tsx
> +  props: VerificationCodeProps
same spiel as above with props

2022-03-09 17:19 UTC, andrewydai commented on components/notifications/modal/VerificationCode.tsx
> +  //
random comment lol

2022-03-09 17:19 UTC, andrewydai commented on components/notifications/modal/VerificationCode.tsx
> +          className={`phone-modal__link ${isDisabled && '--disabled'}`}
for `resendDisabled`, can we maybe set an error message in the the `resendVerificationCode` saying to wait so users know why they aren't getting verification codes back

2022-03-10 16:46 UTC, koulopoulos commented on styles/_PhoneModal.scss
> +    .PhoneInputCountrySelectArrow {
Resolved by [d10b096](https://github.com/sandboxnu/searchneu/pull/157/commits/d10b096b4274a369c68d304705073707e634fd97)

2022-03-10 16:53 UTC, koulopoulos commented on components/Modal.tsx
> +      }
Resolved by [ad1caa0](https://github.com/sandboxnu/searchneu/pull/157/commits/ad1caa04ef27a4c809a43cceca173daad00311b5)

2022-03-10 16:54 UTC, koulopoulos commented on components/Modal.tsx
> +  props: React.PropsWithChildren<Props>
Resolved by [f82bbc6](https://github.com/sandboxnu/searchneu/pull/157/commits/f82bbc6fe7be2019b66c182af4303dd0f1ebd13c)

2022-03-10 16:54 UTC, koulopoulos commented on components/Modal.tsx
> +interface Props {
Resolved by [f82bbc6](https://github.com/sandboxnu/searchneu/pull/157/commits/f82bbc6fe7be2019b66c182af4303dd0f1ebd13c)

2022-03-10 17:03 UTC, koulopoulos commented on components/ResultsPage/Results/NotifSignUpSwitch.tsx
> +    /*<Button className="tester" onClick={onClickWithAmplitudeHook}>
Oops, this component should not exist at all. Resolved by [33e425a](https://github.com/sandboxnu/searchneu/pull/157/commits/33e425a49f1982738afe6527021bffa91d743597)

2022-03-10 17:20 UTC, koulopoulos commented on components/notifications/modal/PhoneNumber.tsx
> +  props: PhoneInputStepProps
Resolved by [9019709](https://github.com/sandboxnu/searchneu/pull/157/commits/901970919f134f9a5503048606a41b6ace5d9ee9)

2022-03-10 18:06 UTC, koulopoulos commented on components/notifications/modal/PhoneNumber.tsx
> +import PhoneInput from 'react-phone-number-input';
Resolved by [47a92d4](https://github.com/sandboxnu/searchneu/pull/157/commits/47a92d48323b1c564f5978c2d0b1a0e24acc4ac1)

2022-03-10 18:10 UTC, koulopoulos commented on components/notifications/modal/SignUpModal.tsx
> +import { MoonLoader } from 'react-spinners';
Resolved by [d3c1602](https://github.com/sandboxnu/searchneu/pull/157/commits/d3c16025096fa0e7edd28262439eb3d61dcb3707)

2022-03-10 18:21 UTC, koulopoulos commented on components/notifications/modal/PhoneNumber.tsx
> +        <PhoneInput
Turns out this was just a bug with my SASS. Resolved by [408c3d7](https://github.com/sandboxnu/searchneu/pull/157/commits/408c3d7dd40e80a7596ff2c5f4bf9b5b301af386)

2022-03-10 18:24 UTC, koulopoulos commented on components/notifications/modal/VerificationCode.tsx
> +  props: VerificationCodeProps
Resolved by [a5dc193](https://github.com/sandboxnu/searchneu/pull/157/commits/a5dc19304e72d0a3b5cb9f12d79566bbe940d361)

2022-03-10 18:24 UTC, koulopoulos commented on components/notifications/modal/VerificationCode.tsx
> +  //
Resolved by [a5dc193](https://github.com/sandboxnu/searchneu/pull/157/commits/a5dc19304e72d0a3b5cb9f12d79566bbe940d361)

2022-03-10 18:43 UTC, koulopoulos commented on components/notifications/modal/SignUpModal.tsx
> +  }, [verificationCode, onSignIn, onSuccess, phoneNumber]);
Resolved by [23d75ef](https://github.com/sandboxnu/searchneu/pull/157/commits/23d75ef43062f1fb797681cbda407d03411cd6f0)

2022-03-10 18:45 UTC, koulopoulos commented on components/notifications/modal/SignUpModal.tsx
> +    const onVerificationCodeSubmit = (): void => {
This was done to avoid linter warnings, but isn't necessary as far as I can tell. Resolved by [23d75ef](https://github.com/sandboxnu/searchneu/pull/157/commits/23d75ef43062f1fb797681cbda407d03411cd6f0)

2022-03-10 19:23 UTC, koulopoulos commented on components/notifications/modal/SignUpModal.tsx
> +enum Status {
Yeah I agree, it was overkill. Resolved by [f641c7b](https://github.com/sandboxnu/searchneu/pull/157/commits/f641c7b300e12a9c17b7f15d618c8d84847af8ea)

2022-03-10 19:23 UTC, koulopoulos commented on __mocks__/style.js
> +module.exports = {};
Resolved by [0f27365](https://github.com/sandboxnu/searchneu/pull/157/commits/0f273656e15d9d97b2ba62fd3e93437d3aeb4070)

2022-03-10 21:32 UTC, koulopoulos commented on components/notifications/modal/VerificationCode.tsx
> +          className={`phone-modal__link ${isDisabled && '--disabled'}`}
I added a countdown to the verification step when resend is disabled. Let me know what you think.
<img width="386" alt="Screen Shot 2022-03-10 at 4 29 47 PM" src="https://user-images.githubusercontent.com/40676764/157758238-d96a2c30-d5d4-42aa-a8d9-4d6149af915c.png">

2022-03-21 21:19 UTC, andrewydai approved these changes
LGTM

2022-03-21 21:30 UTC, hankewyczz approved these changes
🚢 looking good!

2022-03-24 17:21 UTC, merged