Honors Filter
sandboxnu/searchneu-v1 pull request #164
Opened 2022-04-14 21:15 UTC by SimChadha

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

Created Honors toggle that when activated, shows courses with at least one honors section

<br>

# Tickets

###### A link to any tickets this PR is associated with on Trello.

- https://trello.com/c/CQ602Xl2

# Contributors

###### Anyone who contributed to this PR for future reference.

- Simar Chadha
- Adam Koulopoulos

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

-
-
-

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

Currently uses a hard coded timer to allow the toggle to animate before activating the filter. This is not ideal and could be done better with async/await in the future. 

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [x] Has documentation and comments in code
- [ ] Has test coverage for code
- [x] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-04-24 19:06 UTC, andrewydai commented on components/ResultsPage/FilterPanel.tsx
> +import type { Option } from './filters';
remove to fix lint warrning

2022-04-24 19:50 UTC, andrewydai requested changes
Left some comments

2022-04-24 19:50 UTC, andrewydai commented on components/ResultsPage/ToggleFilter.tsx
> +      if (expectedActivationState == isActivated) {
should use triple equals just for style

2022-04-24 19:50 UTC, andrewydai commented on components/ResultsPage/ToggleFilter.tsx
> +          <span className={`react-switch-button`} />
this should probably be the original if there's no js expression in the string literal

2022-04-24 19:50 UTC, andrewydai commented on components/ResultsPage/filters.ts
> +};
Kinda nit but can we move these in order of their filter order

2022-04-24 19:50 UTC, andrewydai commented on components/ResultsPage/filters.ts
> +  honors: HONORS_SPEC,
same here with ordering

2022-04-24 19:50 UTC, andrewydai commented on package.json
> +    "migrate": "^1.7.0",
uh what is this I don't see it being used

2022-04-24 19:50 UTC, andrewydai commented on pages/[campus]/[termId]/search/[query].tsx
> +import _, { filter } from 'lodash';
revert this, probably accidentally imported while typing filter lol

2022-04-24 19:50 UTC, andrewydai commented on components/ResultsPage/ToggleFilter.tsx
> +  function setActiveAfterAnimating() {
I'm assuming this is to fix the issue of animation/async set stating that could cause weird states if the toggle is spammed. I think this is unnecessary after talking with some people. If there's a bug that this covers I could not replicate; pls lmk if there is so we can talk about it. In the mean time, this is what I had for an onChange and it seemed to work without bugs:
`const onChange = event => setActive(event.target.checked)`

2022-04-28 19:05 UTC, SimChadha commented on components/ResultsPage/ToggleFilter.tsx
> +  function setActiveAfterAnimating() {
I still seem to get a visual bug with that solution, but we can talk about it more

2022-04-28 19:32 UTC, andrewydai approved these changes
🚀

2022-04-29 19:49 UTC, merged