Mobile class pages part 2
sandboxnu/searchneu-v1 pull request #165
Opened 2022-04-21 22:54 UTC by puneetjohal

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

<br>

# Tickets

###### A link to any tickets this PR is associated with on Trello.

-

# Contributors

###### Anyone who contributed to this PR for future reference.

-

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

-
-
-

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-04-24 19:00 UTC, andrewydai requested changes
Couple small things

2022-04-24 19:00 UTC, andrewydai commented on components/ClassPage/mobile/MobileClassInfoExpandable.tsx
> +export type MobileClassInfoExpandableProps = {
don't need to export

2022-04-24 19:00 UTC, andrewydai commented on components/ClassPage/mobile/MobileClassInfoExpandable.tsx
> +    // TODO: needs a design
Why don't we have branches for the rest of the supported info types? I see some designs on Figma, unsure if I missed something

2022-04-24 19:00 UTC, andrewydai commented on components/ClassPage/mobile/MobilePageContent.tsx
> +                  {/* <SignUpForNotifications
Do notifs not work rn?

2022-04-24 19:00 UTC, andrewydai commented on components/ClassPage/mobile/MobilePageContent.tsx
> +                <div className="expandables">
This component is getting pretty monstrous, let's maybe use a map here on the object values, either export an array and map over it or use `Object.values(SupportedInfoTypes).map(() => ...)`

2022-04-24 19:00 UTC, andrewydai commented on components/ClassPage/mobile/MobileClassInfoExpandable.tsx
> +    // TODO: needs a design
Nevermind I understand that this is the next part

2022-04-29 06:46 UTC, puneetjohal commented
Added in prereq information. I tried to follow the design as closely as possible, but ultimately chose to simplify it just a little in the interest of time since I was having some trouble parsing out "sequences"/`OR`-ed `AND`s. Here are some examples:

No prereqs (CS2500):
![image](https://user-images.githubusercontent.com/33487680/165889848-6c8a56a1-6d74-4455-a124-5ffb7c08b1a5.png)

One prereq (CS2510):
![image](https://user-images.githubusercontent.com/33487680/165889906-fb6666d3-5617-4767-8db8-f1d8d886ce20.png)

Two `AND`-ed prereqs (CS2810):
![image](https://user-images.githubusercontent.com/33487680/165889973-6d2d39c8-b9a4-4513-85eb-1cc398d0583e.png)

Nested prereqs (CS3000):
![image](https://user-images.githubusercontent.com/33487680/165890048-ff09b336-a52d-4936-9a3a-41b4374044a1.png)

The most complex prereq tree I could find among fall classes (CIVE2221):
![image](https://user-images.githubusercontent.com/33487680/165890196-283aa719-71ee-415f-acc9-37338b6c03b5.png)

I used the same component for coreqs, so they look the same (just without the nesting).

2022-04-30 01:54 UTC, puneetjohal commented on components/ClassPage/mobile/MobilePageContent.tsx
> +                  {/* <SignUpForNotifications
Can this be in a separate PR? I'm out of the loop on mobile notif designs.

2022-04-30 17:14 UTC, andrewydai approved these changes
lgtm!

2022-04-30 17:31 UTC, merged