Add tooltip next to search bar
sandboxnu/searchneu-v1 pull request #168
Opened 2022-09-22 03:12 UTC by sebwittr

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

<br> Adds a tooltip next to the search bar, in order to show the user how to use phrase searches. 

# Tickets

###### A link to any tickets this PR is associated with on Trello.

- https://trello.com/c/LVcD61Yq/318-tooltip-for-phrase-searching

# Contributors

###### Anyone who contributed to this PR for future reference.

- @sebwittr 

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

- Adds a SearchInfoIcon component that contains the icon, along with the tooltip itself.
-
-

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-10-04 14:58 UTC, hankewyczz commented
![image](https://user-images.githubusercontent.com/27775244/193853660-de8592fe-8e14-4c9a-8454-b47a7ac51752.png)

2022-10-08 20:56 UTC, Lucas-Dunker approved these changes
Code is intuitive to understand, looks fine to me; the tooltip is laid under the husky icon when in smaller window sizes, but that seems to be an overall issue with screen sizing not limited to just the tooltip.

2022-10-13 04:01 UTC, sebwittr commented
> ![image](https://user-images.githubusercontent.com/27775244/193853660-de8592fe-8e14-4c9a-8454-b47a7ac51752.png)

This should be fixed with the newest commit!

2022-10-13 19:53 UTC, koulopoulos requested changes
The `z-index` fix looks good 👍 - Just one small comment on the styling.

2022-10-13 19:53 UTC, koulopoulos commented on styles/home/_HomeSearch.scss
>        & > div {
It looks like this selector `.HomeSearch__searchBar--input > div` is causing the new icon to have a faint white border to the left (see attached image). This looks a little awkward and should probably be removed.

<img width="61" alt="Screen Shot 2022-10-13 at 3 48 35 PM" src="https://user-images.githubusercontent.com/40676764/195695298-f018ff1d-e5e4-4c7a-9114-18bde20d4af2.png">

2022-10-16 18:48 UTC, sebwittr commented on styles/home/_HomeSearch.scss
>        & > div {
This should be fixed now

2022-10-16 18:54 UTC, koulopoulos approved these changes
Just noting a style change, but nothing major.

2022-10-16 18:54 UTC, koulopoulos commented on styles/home/_HomeSearch.scss
> -        border-left: 1px solid #e8e8e8;
Looks like the removal of this style also effected the border between the semester dropdown and text input. Not a huge deal, as it's just a difference in the shade of gray, but noting it here.

<img width="156" alt="Screen Shot 2022-10-16 at 2 52 31 PM" src="https://user-images.githubusercontent.com/40676764/196052776-9c9e0d3f-b36a-4d55-aaf1-938e77abac86.png">

2022-10-16 19:07 UTC, hankewyczz requested changes

2022-10-16 19:07 UTC, hankewyczz commented on components/ResultsPage/SearchBar.tsx
> +      <SearchInfoIcon />
Currently, the icon doesn't do anything on mobile. We can do either one of two things:
- Remove it for mobile views
- Have it display the tooltip on click, not just on hover

Also, the home screen has this border on mobile 
![image](https://user-images.githubusercontent.com/27775244/196053117-3b207dbc-e10e-473c-a887-722eacb97321.png)

2022-10-20 03:31 UTC, sebwittr commented on components/ResultsPage/SearchBar.tsx
> +      <SearchInfoIcon />
I got rid of the tooltip for mobile, so these problems shouldn't exist anymore

2022-10-23 20:11 UTC, hankewyczz commented on components/ResultsPage/SearchBar.tsx
> +      {!macros.isMobile ? <SearchInfoIcon /> : <></>}
In the rest of our code, we tend to use `{!macros.isMobile && <SearchInfoIcon />`

(This is just for context to see what's equivalent - I think both ways are confusing and poorly-written (thanks react) so i'm fine with you using either one here)

2022-10-23 20:11 UTC, hankewyczz approved these changes

2022-10-25 22:44 UTC, merged