added waitlists seats to mobile
sandboxnu/searchneu-v1 pull request #170
Opened 2022-09-24 20:11 UTC by DilanRocco

# Purpose
PUT TICKET LINK AND NAME
###### A brief description of the purpose of the PR's changes for the project.

<br>

# Tickets

###### A link to any tickets this PR is associated with on Trello.

-

# Contributors

###### Anyone who contributed to this PR for future reference.

-

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

-
-
-

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-09-29 23:39 UTC, hankewyczz requested changes

2022-09-29 23:39 UTC, hankewyczz commented on styles/results/_MobileSectionPanel.scss
> +  &__waitlist-text {
this class doesn't seem to have any effect - the `span` elements don't actually inherit these styles.

2022-09-30 01:49 UTC, DilanRocco commented on styles/results/_MobileSectionPanel.scss
> +  &__waitlist-text {
the class __waitlist-text has two css attributes: color, and text-wrap. At least visually, I can see that the waitlist seats changes color to gray. Am I missing something else?

2022-09-30 02:41 UTC, koulopoulos requested changes
Just a couple of styling nitpicks 👍

2022-09-30 02:41 UTC, koulopoulos commented on styles/results/_MobileSectionPanel.scss
> +    color: gray;
nit: instead of using `gray` here, we probably want to use an existing shade like `#969696`(the color we use for 'None' for NUPaths/Prerequisites/Corequisites/Course fees)

2022-09-30 02:41 UTC, koulopoulos commented on styles/results/_MobileSectionPanel.scss
> +    white-space: no-wrap;
Does `no-wrap` work here with the hyphen? ime the value needs to be `nowrap` (see [https://developer.mozilla.org/en-US/docs/Web/CSS/white-space](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space))

2022-09-30 13:48 UTC, hankewyczz commented on styles/results/_MobileSectionPanel.scss
> +  &__waitlist-text {
ah, you're right about the color - I was just looking at the wrapping behavior. In this case, following Adam's comment should be fine.

2022-10-02 18:29 UTC, DilanRocco commented on styles/results/_MobileSectionPanel.scss
> +  &__waitlist-text {
understood

2022-10-02 18:30 UTC, DilanRocco commented on styles/results/_MobileSectionPanel.scss
> +    color: gray;
understood, right now I have the color hard coded, not sure if we want to put that into a constants file

2022-10-02 18:31 UTC, DilanRocco commented on styles/results/_MobileSectionPanel.scss
> +    white-space: no-wrap;
yes, you're right. Fixed.

2022-10-02 19:01 UTC, hankewyczz approved these changes
lgtm

2022-10-02 20:04 UTC, koulopoulos commented on styles/results/_MobileSectionPanel.scss
> +    color: gray;
should be fine hard coded for now

2022-10-02 20:04 UTC, koulopoulos approved these changes
🚀🚀🚀

2022-10-02 22:17 UTC, merged