Visual Indication for API Errors
sandboxnu/searchneu-v1 pull request #172
Opened 2022-10-03 02:56 UTC by tiingweii-shii

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

<br>Adds visual indication in the frontend when our API fails (to replace the infinite loading screen). 

# Tickets

###### A link to any tickets this PR is associated with on Trello.
[Set timeout for semester API loading](https://trello.com/c/CLORH0Xe/326-set-timeout-for-semester-api-loading)

-

# Contributors

###### Anyone who contributed to this PR for future reference.

- @tingweishi1@gmail.com

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

- Displays "An Error Occurred : (" with a "Report a Bug" button on Home and Search page when the API fails.

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br> Maybe update the design for the error message

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [x] Is passing linting checks
- [x] Is passing tsc
- [x] Is passing existing tests
- [ ] Has documentation and comments in code
- [x] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-10-06 20:24 UTC, hankewyczz requested changes
Some small changes, but mostly looks good!

2022-10-06 20:24 UTC, hankewyczz commented on components/ResultsPage/useSearch.ts
> +  error: any;
can we use a more precise type here?

2022-10-06 20:24 UTC, hankewyczz commented on components/terms.ts
> +  error: any;
is there a better type?

2022-10-06 20:24 UTC, hankewyczz commented on utils/TermInfoProvider.tsx
> +  error: any;
is there a better type?

2022-10-06 20:24 UTC, hankewyczz commented on styles/pages/_Home.scss
> -    pointer-events: none;
why was this removed?

2022-10-06 20:24 UTC, hankewyczz commented on styles/pages/_Home.scss
> -    pointer-events: none;
![image](https://user-images.githubusercontent.com/27775244/194410929-fe8f2fc2-3b1b-4fcd-8760-5d6087dc3fd4.png)
I think that because of this change, I can't click on the link anymore

2022-10-07 17:46 UTC, Lucas-Dunker commented on components/terms.ts
> +  error: any;
In agreement with Zachar, is there any way this error type can be narrowed down further?

2022-10-07 17:46 UTC, Lucas-Dunker commented on styles/pages/_Home.scss
> -    pointer-events: none;
I'm getting the same issue as above.

2022-10-07 23:43 UTC, tiingweii-shii commented on styles/pages/_Home.scss
> -    pointer-events: none;
Ahhhhh

2022-10-07 23:45 UTC, tiingweii-shii commented on styles/pages/_Home.scss
> -    pointer-events: none;
So the `pointer-events: none;` was removed because it was preventing the Report a Bug button from being clickable. I will look into this.

2022-10-13 21:05 UTC, tiingweii-shii commented on styles/pages/_Home.scss
> -    pointer-events: none;
Update: fixed this issue

2022-10-13 21:06 UTC, tiingweii-shii commented on utils/TermInfoProvider.tsx
> +  error: any;
Yes : )

2022-10-17 15:52 UTC, Lucas-Dunker commented on components/Footer.tsx
> +          Search NEU is built for students by students &amp; is not affiliated
Is this doc change a typo?

2022-10-23 20:08 UTC, hankewyczz requested changes
Looks good, just a small tweak!

2022-10-23 20:08 UTC, hankewyczz commented on components/terms.ts
> +  error: Error;
can you make this type optional (with a `?`, since the error might be `null`)?

2022-10-23 20:08 UTC, hankewyczz commented on pages/[campus]/[termId]/search/[query].tsx
> +                <h3> An Error Occurred : ( </h3>
Has Vanessa reviewed the phrasing of this error message?

2022-10-30 19:15 UTC, tiingweii-shii commented on pages/[campus]/[termId]/search/[query].tsx
> +                <h3> An Error Occurred : ( </h3>
YES :D

2022-10-30 19:21 UTC, tiingweii-shii commented on components/Footer.tsx
> +          Search NEU is built for students by students &amp; is not affiliated
This should be fine. "&amp;" should be displayed as "&" in the frontend : )

2022-10-30 22:48 UTC, hankewyczz approved these changes
looks good! 😸

2022-11-04 04:24 UTC, merged