Sw class page error
sandboxnu/searchneu-v1 pull request #180
Opened 2022-11-02 01:50 UTC by sebwittr

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

<br> An error would occur on class pages when you refreshed or opened them on a new tab. This would occur because it would try loading information when the classId or subject were still empty. 

# Tickets

###### A link to any tickets this PR is associated with on Trello.

-

# Contributors

###### Anyone who contributed to this PR for future reference.

- @sebwittr 

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

- Added a check within a useEffect, to only get the class information when subject and classInfo were not empty.
-
-

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-11-02 01:55 UTC, sebwittr commented
![classPageError](https://user-images.githubusercontent.com/79394243/199376239-6b33e503-3280-40a8-a8cc-c54e99f37e44.PNG)

The error occurring.

2022-12-04 21:02 UTC, DilanRocco approved these changes

2022-12-04 22:54 UTC, hankewyczz requested changes
Two tiny tweaks, but looks good!

2022-12-04 22:54 UTC, hankewyczz commented on pages/[campus]/[termId]/classPage/[subject]/[classId].tsx
> +  console.log('CLASSID: ' + classId);
Remove

2022-12-04 22:54 UTC, hankewyczz commented on pages/[campus]/[termId]/classPage/[subject]/[classId].tsx
> +    if (subject != '' && classId != '') {
```suggestion
    if (subject !== '' && classId !== '') {
```

2023-01-29 19:32 UTC, hankewyczz reviewed
a few more minor changes 👀

2023-01-29 19:32 UTC, hankewyczz commented on components/ClassPage/PageContent.tsx
> -      ) : (
[nit] remove `router` on 26

2023-01-29 19:32 UTC, hankewyczz commented on components/ClassPage/mobile/MobilePageContent.tsx
> -      <div className="backToResults" onClick={() => router.back()}>
[nit] get rid of `router` on 45

2023-01-29 19:32 UTC, hankewyczz commented on pages/down.tsx
> +import React, { ReactElement } from 'react';
I'm not sure where this snuck in, but we don't want to re-introduce the down pages. Maybe try merging from master again? If that doesn't work, just remove these files manually.

2023-01-29 19:32 UTC, hankewyczz commented on pages/[campus]/[termId]/classPage/[subject]/[classId].tsx
> +    if (subject !== '' && classId !== '') {
I should've thought about this sooner, but this should be in `loadClassPageInfo`. If the user gives us a blank subject/classId, we should yeet them to `/404`

2023-02-03 20:05 UTC, sebwittr commented on pages/down.tsx
> +import React, { ReactElement } from 'react';
The down page is still up on prod I think

2023-02-03 21:07 UTC, hankewyczz commented on pages/down.tsx
> +import React, { ReactElement } from 'react';
Sorry, I phrased this poorly. 

Yes, the page is on prod, but it's not on the mobile-class-pages branch. We don't want to re-introduce it here, because it'll cause issues when we later merge into prod.

Instead of pulling from master (my mistake), putting from `mobile-class-pages-main` should be the default for this branch.

2023-02-08 21:06 UTC, sebwittr commented on pages/[campus]/[termId]/classPage/[subject]/[classId].tsx
> +    if (subject !== '' && classId !== '') {
I think this might cause some problems. I think when the component first loads subject and classId might both initially be empty or null, which would cause the redirect to 404.

2023-02-08 21:06 UTC, sebwittr commented on pages/[campus]/[termId]/classPage/[subject]/[classId].tsx
> +    if (subject !== '' && classId !== '') {
I'll experiment a little bit with it though

2023-02-08 22:03 UTC, hankewyczz commented on pages/[campus]/[termId]/classPage/[subject]/[classId].tsx
> +    if (subject !== '' && classId !== '') {
Ah, you're right — disregard my comment. I forgot the purpose of this was waiting until subject/class gave us a non-null value

2023-02-13 23:27 UTC, hankewyczz approved these changes
🚀

2023-03-01 23:02 UTC, Lucas-Dunker approved these changes

2023-03-03 23:27 UTC, merged