Fixed alter banner styling and commented it out...
sandboxnu/searchneu-v1 pull request #181
Opened 2022-11-04 02:17 UTC by tiingweii-shii

# Purpose

###### 
<img width="1431" alt="Screen Shot 2022-11-03 at 10 07 23 PM" src="https://user-images.githubusercontent.com/57331456/199869857-2f6da53d-4ae1-4cd8-84dd-5438ef5d0b86.png">
The alter banner styling is a little off and it is no longer needed, so we have decided to fix it and commented it out...
<br>

# Tickets

###### A link to any tickets this PR is associated with on Trello.

NA

# Contributors

###### Anyone who contributed to this PR for future reference.

- @tiingweii-shii 

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.
Now the alter banner looks like this : )
<img width="1429" alt="Screen Shot 2022-11-03 at 10 11 20 PM" src="https://user-images.githubusercontent.com/57331456/199870170-6d8f5420-7ce1-4a72-8a79-ada8aaf6deab.png">
 but it is commented out so the Home page looks like this...
 
<img width="1432" alt="Screen Shot 2022-11-03 at 10 12 25 PM" src="https://user-images.githubusercontent.com/57331456/199870320-92e432f8-44c1-4e0f-83f9-c40ed7c8a019.png">

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.
<br> I like the alter banner message :D

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [x] Is passing linting checks
- [ ] Is passing tsc
- [x] Is passing existing tests
- [ ] Has documentation and comments in code
- [x] Has test coverage for code
- [x] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-11-04 03:05 UTC, hankewyczz approved these changes
👍 🚧🍿🥨🛴🧨🎈👓🥼🎨🧥🧵🧶👔🏐🏀⚾🥎⚽⛑👒🥿🥾🧤🧣👑🎳🎱🏉🏈🤿

2022-11-06 23:48 UTC, DilanRocco commented
!

2022-11-07 02:48 UTC, Lucas-Dunker approved these changes

2022-11-07 03:57 UTC, hankewyczz requested changes
Could you please pull from `master` and resolve the conflicts?

2022-11-11 16:37 UTC, hankewyczz approved these changes

2022-11-11 16:37 UTC, merged