Added Cool Tooltip
sandboxnu/searchneu-v1 pull request #182
Opened 2022-11-06 22:32 UTC by Lucas-Dunker

# Purpose

###### A brief description of the purpose of the PR's changes for the project.
Adds a tooltip for _negative_ seatcounts explaining why they are negative (a course advisor set an override for a student to take a course)
<br>

# Tickets

###### A link to any tickets this PR is associated with on Trello.

[-Trello Link](https://trello.com/c/F9Qz43pi/313-info-tooltip-for-negative-seat-count)

# Contributors

###### Anyone who contributed to this PR for future reference.

- @sebwit20 

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.
![image](https://user-images.githubusercontent.com/93111430/200198644-1d9e8ece-5a56-4f84-b3a2-f429bb448fb4.png)

-Adds tooltip for negative seat counts explaining why they are negative
-Changed tooltip color for all tooltips to better fit SearchNEU's color palette
-Added better padding for all tooltips

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.
*

<br>

# Checklist

- [x] Filled out PR template :wink:
- [x] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-11-07 04:06 UTC, hankewyczz requested changes
Looks good for the most part, just some questions/minor changes. 

A general note - when making styling changes that aren't universal (in this case - only applicable to specific sections), it's always helpful to include a link in the PR. 

For example - here's a search link for `POLS4500`, Fall 2022 semester, which has negative seats left: https://searchneu-git-ldnegativetooltip-sandboxneu.vercel.app/NEU/202310/search/POLS4500

Also - that link above cuts off the tooltip for me. Could it maybe be aligned to the left, so it doesn't get cut off?

![image](https://user-images.githubusercontent.com/27775244/200224084-f7f39984-07a1-4c06-8232-7ace98c8ff3f.png)

2022-11-07 04:06 UTC, hankewyczz commented on components/common/NegativeSeatCountTooltip.tsx
> +export default function SearchInfoIcon() {
Shouldn't this be `NegativeSeatCount...` or similar? Not `SearchInfo..`

2022-11-07 04:06 UTC, hankewyczz commented on components/common/NegativeSeatCountTooltip.tsx
> +    <div className="SearchInfoIcon">
naming - since this isn't related to the search info, can we find a more general name for that icon?

2022-11-07 04:06 UTC, hankewyczz commented on styles/_SearchInfoIcon.scss
> +      background: #1d3557;
Whenever making styling changes like this, make sure to talk to Vanessa to get her signoff on it (and make a note of it in the PR)

2022-11-07 04:06 UTC, hankewyczz commented on styles/results/_DesktopSectionPanel.scss
> +  > td:nth-child(3) {
what does this change do?

2022-11-07 04:06 UTC, hankewyczz commented on styles/results/_DesktopSectionPanel.scss
> +
what do these changes do?

2022-11-07 04:06 UTC, hankewyczz commented on components/ResultsPage/Results/SectionPanel.tsx
> +        <div className="DeskopSectionPanel__seatcount">
Can y'all talk to Vanessa - should we show something similar on mobile search results? We can't do a tooltip, but maybe just a text element whenever a section has a negative seat count?

2022-11-07 04:08 UTC, sebwittr commented on styles/results/_DesktopSectionPanel.scss
> +  > td:nth-child(3) {
I think the & is just unnecessary for that one

2022-11-07 04:09 UTC, sebwittr commented on components/ResultsPage/Results/SectionPanel.tsx
> +        <div className="DeskopSectionPanel__seatcount">
We got her approval for all the other changes, we'll ask about what we should do on mobile.

2022-11-07 04:15 UTC, sebwittr commented on styles/results/_DesktopSectionPanel.scss
> +
CSS was giving us weird problems with having these classes where they previously were, since we changed the HTML and wrapped them inside a div (Basically it wasn't respecting the styling anymore, since there was another layer). I don't think the red, yellow, or green classes were being used elsewhere so I thought the best solution was to bring them outside the styling of the td, which fixed our problem.

2022-11-07 04:16 UTC, sebwittr commented on styles/_SearchInfoIcon.scss
> +      background: #1d3557;
Vanessa approved this color change!

2022-11-15 23:09 UTC, Lucas-Dunker commented on components/ResultsPage/Results/SectionPanel.tsx
> +        <div className="DeskopSectionPanel__seatcount">
> Looks good for the most part, just some questions/minor changes.
> 
> A general note - when making styling changes that aren't universal (in this case - only applicable to specific sections), it's always helpful to include a link in the PR.
> 
> For example - here's a search link for `POLS4500`, Fall 2022 semester, which has negative seats left: https://searchneu-git-ldnegativetooltip-sandboxneu.vercel.app/NEU/202310/search/POLS4500
> 
> Also - that link above cuts off the tooltip for me. Could it maybe be aligned to the left, so it doesn't get cut off?
> 
> ![image](https://user-images.githubusercontent.com/27775244/200224084-f7f39984-07a1-4c06-8232-7ace98c8ff3f.png)

The textbox is only cut off at smaller resolutions, which Seb and I believe is expected; we messed around with having the tooltip box expand with text to the left instead of the right, but we couldn't get it working unfortunately. We're worried that messing with the box sizing might mess up the arrow at the top of the box as well.

2022-11-15 23:17 UTC, hankewyczz commented on components/ResultsPage/Results/SectionPanel.tsx
> +        <div className="DeskopSectionPanel__seatcount">
"expected" as in "this is desired behavior" or "given how the code is now, this is how it works"?

Either way — we don't want to leave it in this state. Don't modify the existing `Tooltip`, but expand it. An idea could be to add a `prop` which allows us to optionally define which direction (left/right) the tooltip is oriented in.

2022-11-15 23:29 UTC, Lucas-Dunker commented on components/ResultsPage/Results/SectionPanel.tsx
> +        <div className="DeskopSectionPanel__seatcount">
Great suggestion, we'll expand `prop` and get some direction functionality working.

2022-11-21 14:23 UTC, hankewyczz reviewed
99.9%!!! I just have two tiny nits

2022-11-21 14:23 UTC, hankewyczz commented on components/Tooltip.tsx
> +  flipLeft?: boolean;
Could this be a little more descriptive? We want a name that explains that if this flag is `true`, then the body of the tooltip will be oriented to the left of the tooltip arrow. (edit — I see that this is a prop passed directly to the Tooltip, so maybe you can't change the name. If that's the case, you'll still want to document its use)

That's a little hard to fit into a variable name, so you'll definitely want to add a JSDoc comment right above that variable, in the props. (JSDoc > normal comment, because in most IDEs, if you hover over a variable/attribute/property/function with a JSDoc comment, you'll see it in a little tooltip. That's not the case w/ normal comments)

2022-11-21 14:23 UTC, hankewyczz commented on components/ResultsPage/Results/SectionPanel.tsx
> +          </span>{' '}
Why do we need this?

EDIT: if we really need this space, I'd prefer if you just added a non-breaking space (`&nbsp;`) in the inner span (ie. right before "Negative"), just to keep those two related components together.

2022-12-04 20:37 UTC, hankewyczz requested changes
https://searchneu-7qan0f8ps-sandboxneu.vercel.app/NEU/202330/search/is4300

![image](https://user-images.githubusercontent.com/27775244/205514185-20246e9c-2334-4b20-ac55-82b53f280522.png)

The tooltip looks off-center for me - could we change that?

2022-12-04 20:37 UTC, hankewyczz commented on components/ResultsPage/Results/SectionPanel.tsx
> +              text="Negative seat counts are displayed when students override into a course."
I'd like to expand this text a little bit, to add more context (what is an "override"?)

So, two options:
- Add a link to the word "override" to [this article](https://registrar.northeastern.edu/article/student-registration-overrides/)
  - Right now, the tooltip component takes text, not HTML elements. However, this should be a relatively straightforward change
- Change the text phrasing to make it clear that an "override" is something that an academic advisor does on behalf of a student. For example: "Negative seat counts are displayed when academic advisors apply course overrides for students."

I'm fine with either one; the second option is definitely easier, so I'm fine with you guys doing that.

2022-12-04 21:05 UTC, Lucas-Dunker commented
New Alignment: ![image](https://user-images.githubusercontent.com/93111430/205515513-4aa52d88-81c1-4157-9035-a07461a3034d.png)

New Color Scheme + Alignment:  
![image](https://user-images.githubusercontent.com/93111430/205515526-1f290c9a-8e91-424a-80e9-ed010059e1d7.png)

2022-12-04 21:48 UTC, DilanRocco commented
The spacing between the two lines of text look off
<img width="1013" alt="Screenshot 2022-12-04 at 4 47 43 PM" src="https://user-images.githubusercontent.com/68393684/205517395-664eefb3-ade7-4a37-81f3-5bf525e1222a.png">

2022-12-04 22:51 UTC, hankewyczz requested changes
One more tiny thing

2022-12-04 22:51 UTC, hankewyczz commented on components/ResultsPage/Results/SectionPanel.tsx
> -              text="Negative seat counts are displayed when students override into a course."
The mobile version should also be updated. I recommend making a top-level variable for the negative seat tooltip text, so that there is only one place to change the text.

2023-02-15 04:54 UTC, hankewyczz commented
@Lucas-Dunker 

Small CSS tweak:
![image](https://user-images.githubusercontent.com/27775244/218935015-e85d78fb-a652-4739-8c89-37fbcc02e5dd.png)

we've got a little clipping on the tooltip icon (but only at certain zoom levels — not sure why).

Also, the tooltip isn't fully aligned with the text box

2023-03-01 22:50 UTC, hankewyczz approved these changes

2023-03-31 13:57 UTC, sebwittr approved these changes

2023-03-31 15:02 UTC, merged