Semesters Names Inconsistency on Law/CPS Class Pages
sandboxnu/searchneu-v1 pull request #185
Opened 2022-11-08 04:52 UTC by tiingweii-shii

# Purpose

<br> CPS/LAW use different semester names than NEU, but it is not reflected on course info pages. This PR addresses the semester name inconsistencies :)

# Tickets

https://trello.com/c/G5MKa3nX/260-semesters-for-law-cps-classes-dont-match-up-on-class-pages

# Contributors

@tingweishi1@gmail.com

# Feature List

- Updated the logic for parsing semester names from termIds (to include semester names for CPS and LAW)

# Notes
<br>see comment 👀 

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [x] Is passing linting checks
- [x] Is passing tsc
- [x] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [x] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-11-08 05:04 UTC, tiingweii-shii commented on components/terms.ts
> +  if (seasonDigit < 3) {
I think "correcting" the year for Fall and Winter semesters is pretty thoughtful and it is consistent with the Homepage semester, but it seems like the Winter semester (for CPS and LAW) is not set correctly on Homepage (e.g. termId 202325 is Winter 2023, but it should be Winter 2022 to be consistent).

I may push another commit to fix this, but thats a problem for tomorrow...

2022-11-11 17:00 UTC, hankewyczz requested changes
We have the TermInfoContext - could we use that for the names instead of using a mapping?

2022-11-11 17:00 UTC, hankewyczz commented on components/terms.ts
> +  if (!semesterDigitMap[semesterDigit])
```suggestion
  if (semesterDigitMap[semesterDigit] === undefined)
```

2022-11-11 17:00 UTC, hankewyczz commented on components/terms.ts
> +  if (seasonDigit < 3) {
We want to stay consistent with what Banner gives us [[link]](https://nubanner.neu.edu/StudentRegistrationSsb/ssb/classSearch/getTerms?offset=1&max=200&searchTerm=)

So, Fall 2022-23 is "Fall 2022", but Winter 2022-23 is "Winter 2023"

This function should only modify the Fall names.

2022-11-20 21:36 UTC, tiingweii-shii commented on components/ClassPage/PageContent.tsx
> +        // probably should include this in the backend as well
This should be handled in the backend. Cabbage says he will cut a ticket for this.

2023-03-01 22:51 UTC, closed without merging