Api error page
sandboxnu/searchneu-v1 pull request #199
Opened 2023-01-29 21:58 UTC by pranavphadke1

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

<br>

# Tickets

###### A link to any tickets this PR is associated with on Trello.

-

# Contributors

###### Anyone who contributed to this PR for future reference.

-

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

-
-
-

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2023-02-08 00:51 UTC, pranavphadke1 commented
Note: 
- Will probably use this error page as default. Should prob change the page name to something cleaner than "/apiError"
- I believe the only "error" we can get from the useSearch function in "pages/campus/termid/search/query.tsx" is "TypeError: Network request failed", which I believe can only happen if the API isn't working. If this is the case, maybe we should just redirect to this new error page in a similar fasion as we do in the homepage (termid.tsx): 
- useEffect(router.push(apiErrorPage), [error]);

2023-02-09 01:43 UTC, pranavphadke1 commented
Need to do:
- Rename page to "error"
- Implement Vanessa's new Button design
- Experiment with z-index to fix mobile page viewing size issue
- Redirect to error page when searching with API down
- Console log the specific error we run into

2023-02-12 21:20 UTC, pranavphadke1 commented
These are the console log messages I added @hankewyczz 

When redirected to error page from the main page:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/91645231/218337781-1b964ccf-b9a4-45b4-a5b7-4c9509bfd107.png">

When redirected to error page from a failed search:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/91645231/218337858-4e7fa597-c32c-4920-a483-bfcf0d7185a0.png">

2023-02-15 22:54 UTC, hankewyczz requested changes

2023-02-15 22:54 UTC, hankewyczz commented on pages/error.tsx
> +  };
```suggestion
  const toggleModal = () => setModalOpen(!modalOpen);
```
a small nit

2023-02-15 22:54 UTC, hankewyczz commented on pages/error.tsx
> +    <>
Can we not just use the top-level `div` here?

2023-02-15 22:54 UTC, hankewyczz commented on pages/error.tsx
> +                    href="https://github.com/sandboxnu/searchneu"
```suggestion
                    href="https://github.com/sandboxnu/searchneu/issues/new"
```

2023-02-15 22:54 UTC, hankewyczz commented on styles/pages/_Error.scss
> +  }
I'm not a fan of this pattern — I think it could be simplified. 

I think the ideal setup would be using flex columns — https://css-tricks.com/snippets/css/a-guide-to-flexbox/

When the screen is wide enough, it's a grid with two columns, one row (the husky in the rightmost cell)

When it isn't, it's a grid with one column and two rows (husky in the bottom cell).

Tbh, we could use flexbox for more of the elements here, like arranging the buttons. This shouldn't be something we have to create on our own.

2023-03-01 05:19 UTC, pranavphadke1 commented
@hankewyczz Redid the CSS using flexbox. This helped remove a lot of hard-coded styling and also got rid of the need for z-index.

Overall, reduced majority of @ media calls. However, they are still some necessary usage such as adding flex-wrap to the "error-container" class. Also needed to use it to handle the vertical orientation on mobile screens.

2023-03-01 05:19 UTC, pranavphadke1 commented
@Lucas-Dunker ready for review

2023-03-01 22:57 UTC, Lucas-Dunker approved these changes
Looks good to me!

2023-03-03 22:41 UTC, sebwittr commented on pages/[campus]/[termId].tsx
> +      console.log("We've encountered an error: " + termInfosError);
You should get rid of any console.logs you accidentally leave in.

2023-03-04 23:39 UTC, pranavphadke1 commented on pages/[campus]/[termId].tsx
> +      console.log("We've encountered an error: " + termInfosError);
These are to let users know what specific error occured (if they're curious). This was something Zachar asked to add. Is this how you want this implemented? @hankewyczz ?

2023-03-12 18:16 UTC, sebwittr approved these changes
Code looks good! I noticed a typo in the code, but it doesn't matter too much.

2023-03-12 18:16 UTC, sebwittr commented on pages/error.tsx
> +                      className="suport-button"
typo: probably should be "support button"

2023-03-12 18:17 UTC, sebwittr commented on pages/[campus]/[termId].tsx
> +      console.log("We've encountered an error: " + termInfosError);
ok cool sounds good then!

2023-03-12 22:19 UTC, hankewyczz approved these changes
Approved, but two quick things first:
- Try to remove any `!important` cases which aren't necessary
- Double-check with Vanessa (send her the staging link) that the design is OK

Looks great!

2023-03-12 22:19 UTC, hankewyczz commented on styles/pages/_Error.scss
> +  display: flex !important;
Try to make sure that all `!important` uses are actually needed — if not, we don't want to introduce too many (not saying this one is unnecessary, just asking for a second lookthrough)

2023-03-12 22:19 UTC, hankewyczz commented on styles/pages/_Error.scss
> +  font-family: Montserrat Alternates;
```suggestion
  font-family: 'Montserrat Alternates';
```

2023-03-19 19:58 UTC, merged