Update README
sandboxnu/searchneu-v1 pull request #200
Opened 2023-02-15 22:26 UTC by hankewyczz

2023-02-20 18:31 UTC, Lucas-Dunker requested changes
Zachar's LinkedIn hyperlink seems to lead to a 404, just wanted to let you know before approving

2023-02-20 18:33 UTC, hankewyczz commented on readme.md
> +- Zachar Hankewycz <a href="https://github.com/hankewyczz"><img src="./public/images/github.png" alt="Github" width="12px"></a> <a href="https://www.linkedin.com/in/hankewycz.z/"><img src="./public/i
```suggestion
- Zachar Hankewycz <a href="https://github.com/hankewyczz"><img src="./public/images/github.png" alt="Github" width="12px"></a> <a href="https://www.linkedin.com/in/hankewycz-z/"><img src="./public/images/linkedin.png" alt="LinkedIn" width="12px"></a> <a href="https://zacharhankewycz.com/"><img src="./public/images/link.png" alt="Website" width="12px"></a>
```

2023-02-20 18:40 UTC, Lucas-Dunker approved these changes

2023-02-21 05:01 UTC, tiingweii-shii requested changes

2023-02-21 05:01 UTC, tiingweii-shii commented on readme.md
> +- Tingwei Shi
Can you please add my LinkedIn...? https://www.linkedin.com/in/tingwei-shi/

2023-02-22 00:19 UTC, hankewyczz commented on readme.md
> +- Tingwei Shi
```suggestion
- Tingwei Shi <a href="https://www.linkedin.com/in/tingwei-shi/"><img src="./public/images/linkedin.png" alt="LinkedIn" width="12px"></a>
```

2023-02-22 00:30 UTC, tiingweii-shii reviewed
Looks like the github for Lucas, Ally, Pranav, and Sam is linked to github.com instead of their github profile 👀

2023-02-22 00:39 UTC, Lucas-Dunker commented
Same as Tingwei, the links seems to just be github.com

2023-02-22 00:46 UTC, hankewyczz commented on readme.md
> +- Sam Lyon <a href="https://github.com/"><img src="./public/images/github.png" alt="Github" width="12px"></a> <a href="https://www.linkedin.com/in/samclyon/"><img src="./public/images/linkedin.png" a
```suggestion
- Lucas Dunker <a href="https://github.com/Lucas-Dunker"><img src="./public/images/github.png" alt="Github" width="12px"></a> <a href="https://www.linkedin.com/in/lucasdunker/"><img src="./public/images/linkedin.png" alt="LinkedIn" width="12px"></a>
- Vanessa Peng <a href="https://www.linkedin.com/in/vanessa-peng"><img src="./public/images/linkedin.png" alt="LinkedIn" width="12px"></a> <a href="https://vanessapeng.com"><img src="./public/images/link.png" alt="Website" width="12px"></a>
- Ally Chao <a href="https://github.com/allychao"><img src="./public/images/github.png" alt="Github" width="12px"></a> <a href="https://www.linkedin.com/in/ally-chao/"><img src="./public/images/linkedin.png" alt="LinkedIn" width="12px"></a>
- Pranav Phadke <a href="https://github.com/pranavphadke1"><img src="./public/images/github.png" alt="Github" width="12px"></a> <a href="https://www.linkedin.com/in/pranav-phadke/"><img src="./public/images/linkedin.png" alt="LinkedIn" width="12px"></a>
- Sam Lyon <a href="https://github.com/soulwa"><img src="./public/images/github.png" alt="Github" width="12px"></a> <a href="https://www.linkedin.com/in/samclyon/"><img src="./public/images/linkedin.png" alt="LinkedIn" width="12px"></a> <a href="https://soulware.us/"><img src="./public/images/link.png" alt="Website" width="12px"></a>
```

2023-02-22 02:18 UTC, Lucas-Dunker approved these changes

2023-02-23 04:30 UTC, tiingweii-shii approved these changes
I approve 🦦

2023-03-01 03:07 UTC, pranavphadke1 approved these changes

2023-03-01 22:46 UTC, merged