Ac/see all notifications
sandboxnu/searchneu-v1 pull request #201
Opened 2023-02-26 21:38 UTC by sebwittr

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

Displaying subscriptions on a new /subscriptions page. In the future it'll allow users to manage their notifications.  

<br>

# Tickets

###### A link to any tickets this PR is associated with on Trello.

- https://trello.com/c/rDkIeqEm/248-let-users-view-all-notifications

# Contributors

###### Anyone who contributed to this PR for future reference.

- @sebwittr @allychao 

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

- Created a new page for users to view all subscriptions
- 
-

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

This PR should not be merged until full design is implemented! 

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2023-03-03 23:07 UTC, hankewyczz commented
@sebwittr can you add a short sentence to the top of the page noting that this is a WIP page?

2023-03-12 22:34 UTC, hankewyczz requested changes

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +  const [userInfo, setUserInfo] = useState<UserInfo>(null);
```suggestion
  const [userInfo, setUserInfo] = useState<UserInfo | null>(null);
```
We're trying to switch to strict null checking in the near future

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +  const [fetching, setFetching] = useState(true);
```suggestion
  const [subscriptions, setSubscriptions] = useState([]);
  const [isFetching, setIsFetching] = useState(true);
```
[nit] for consistency, I prefer using `const [X, setX]` — you can easily tell which setter sets which constant.

Also, I think `isFetching` is clearer in the predicate form (instead of `fetching`)

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +    const token = cookies.get('SearchNEU JWT');
I had no idea this is how we manage the cookies, but this is incredibly fragile (what if we change the cookie name?) Also, we repeat this code in two other places. 

Could this functionality be abstracted out into a single utils file? We may have an existing spot that's a good fit for it, but that's up to you.

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +    const fetchNotifs = async () => {
Try to break this out into at least two separate functions (each doing one chunk of work). Large functions like this are harder to debug, and harder to review/harder for people to onboard onto and understand.

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +        let termId = '';
```suggestion
```

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +        for (let i = 0; i < userInfo.sectionIds.length; i++) {
```suggestion
        for (const sectionId of userInfo.sectionIds) {
```

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +          });
Two issues here:
- We don't want to be manually parsing these hashes to get the information out
- We can just use the `getSectionInfoByHash` method on `gqlClient` to get the section we care about.

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +            for (let j = 0; j < result.search.nodes[0].sections.length; j++) {
Try using the `const .... of ...` pattern for iterators like this.

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +                    <div>Time: 100</div>
What's this?

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +
This should be a separate function. Just like above, we have another API method to get class data via its hash, so no need to do this manually.

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +      console.log('subscription error with employees');
We'll want to log the actual error as well.

2023-03-12 22:34 UTC, hankewyczz commented on pages/subscriptions.tsx
> +    }, 300);
What's the purpose of this?

2023-03-27 17:36 UTC, sebwittr commented on pages/subscriptions.tsx
> +    }, 300);
oops I forgot to remove this, but it was to test out a fetching animation lol.

2023-03-30 13:09 UTC, Lucas-Dunker requested changes

2023-03-30 13:09 UTC, Lucas-Dunker commented on pages/subscriptions.tsx
> +export default function SubscrptionsPage(): ReactElement {
```suggestion
export default function SubscriptionsPage(): ReactElement {
```

Small typo

2023-11-05 20:41 UTC, Lucas-Dunker approved these changes
Looks good! @pranavphadke1 and @ananyaspatil , make sure to carefully review as well and send feedback if you have any

2023-12-03 21:03 UTC, pranavphadke1 approved these changes

2024-02-04 19:25 UTC, closed without merging