Update Color Scheme To Sass Variables, Replace Sass @Import with @Use
sandboxnu/searchneu-v1 pull request #208
Opened 2023-04-19 06:25 UTC by Lucas-Dunker

# Purpose

_In 2-3 sentences - what does this code actually do, and why?_

I TOLD YOU I WOULD DO IT TONIGHT!

This ticket is pretty self-explanatory; it refactors pretty much **every** color used in Search to a variable in-line with our color scheme (thanks, @vanessa-peng!) with the added bonus of changing our Sass use of @ import to @ use ([here's why](https://sass-lang.com/documentation/at-rules/import))

# Tickets

_What Trello tickets (if any) are associated with this PR?_

-[This one!](https://trello.com/c/o7uqfcwh/383-update-fe-color-scheme)

# Contributors

_Who worked on this PR? Tag them with their Github `@username` for future reference_

@Lucas-Dunker 

Use the **"Assignees"** feature in Github

# Feature List

_Expand on the purpose - what does this code do, and how? This should be a list of the changes, more in-depth and technical_

-Standardizes a SearchNEU color scheme for future use (as a result, some of the colors look different; @vanessa-peng please review!)

-Refactors most color hex codes to a color variable, both in `.tsx` files with the use of `_exports.module.scss` and in `.scss` files with the use of `_variables.csss`

-Changes our imports in Sass to use to protect from future deprecation

# Pictures

_If there are visual changes, show a before/after view, and add a link to the after view using the staging environment._

# Reviewers

Primary reviewer:

- Pick one primary reviewer
  - The team member with the most relevant knowledge about the code area this PR touches
  - **NOT** an author of the PR
  - If the primary reviewer is the project lead, _select two primary reviewers_
    - Goal: facilitate knowledge transfer to other team members
  - Primary reviewers **are required to approve the PR** before it can be merged

**Primary**:

@hankewyczz 
@sebwittr 

Secondary reviewers:

- Pick as many as appropriate — anyone who would benefit from reading the PR
  - Tag them using their Github usernames below

**Secondary**:

@pranavphadke1 
@vanessa-peng

2023-04-25 18:54 UTC, Lucas-Dunker commented on components/ClassPage/SectionsTermNav.tsx
> -          fill={leftNavDisabled(currTermIndex) ? '#969696' : '#000000'}
Don't get scared at the total amount of files changed haha, most are simple color substitutions like this one.

2023-04-25 18:54 UTC, Lucas-Dunker commented on components/ResultsPage/MobileSearchOverlay.tsx
> +import Colors from '../../styles/_exports.module.scss';
This is the import for using color variables in Typescript

2023-04-25 18:54 UTC, Lucas-Dunker commented on components/icons/IconArrow.tsx
> +  fill = '#4e525a',
A big part of this ticket was standardizing our color scheme (using [this](https://www.figma.com/file/ribLh5rcpGvejjQoTCODJX/%F0%9F%8E%A8-SearchNEU-Design-System---WIP?node-id=0-1) as a reference); additionally, I decided not to use color variables for SVG's, since I thought it wouldn't add much additional values compared to actual `tsx` or `sass` files

2023-04-25 18:54 UTC, Lucas-Dunker commented on components/icons/IconUser.tsx
> +    <circle cx="14" cy="14" r="13" stroke="#a8d8dc" strokeWidth="2" />
Another standardization was making uppercase hex codes lowercase!

2023-04-25 18:54 UTC, Lucas-Dunker commented on generated/graphql.ts
> +  totalCount: Scalars['Int'];
I believe this was because of a change from another ticket, but I'm not sure; @hankewyczz thoughts?

2023-04-25 18:54 UTC, Lucas-Dunker commented on index.d.ts
> +declare module '*.scss' {
Adding `scss` files to the file types that typescript can read

2023-04-25 18:54 UTC, Lucas-Dunker commented on jest.config.js
> +    '^.+\\.(css|less|scss)$': '<rootDir>/__mocks__/style.js',
Letting our testing library understand `scss` files

2023-04-25 18:54 UTC, Lucas-Dunker commented on styles/_AlertBanner.scss
> +@use 'variables' as Colors;
This is the import for `scss` files!

2023-04-25 18:54 UTC, Lucas-Dunker commented on styles/_variables.scss
> +//SearchNEU Color Palette
All of the colors SearchNEU now uses! (aside from the colors forming the gradient on the background of the homepage)

2023-04-25 18:56 UTC, Lucas-Dunker commented on styles/_variables.scss
> +
All of the colors SearchNEU now uses! (aside from the colors forming the gradient on the background of the homepage)

2023-04-25 18:57 UTC, Lucas-Dunker commented on styles/_variables.scss
> +$Light_Blue: #b5cad8;
All of the colors SearchNEU now uses! (aside from the colors forming the gradient on the background of the homepage)

2023-04-27 17:43 UTC, hankewyczz requested changes

2023-04-27 17:43 UTC, hankewyczz commented on components/ResultsPage/FeedbackModal/FeedbackModal.tsx
> -          <LogoInput height="14" width="18" fill="#d41b2c" />
Why was this change made & why doesn't it have a variable? (edit: isn't this `neu_red`?)

2023-04-27 17:43 UTC, hankewyczz commented on components/common/AlertBanner.tsx
> -            <IconClose fill="#808080" />
Two issues:
- `Colors.gray` doesn't seem to exist? It's `grey`, not `gray`
- `Colors.grey` is a different shade of grey than `#6a7079`.

2023-04-27 17:43 UTC, hankewyczz commented on components/icons/Husky.tsx
> -          fill="#fff"
Why was this change made?

2023-04-27 17:43 UTC, hankewyczz commented on components/notifications/modal/SignUpModal.tsx
> -            <MoonLoader color={'#7fc4c7'} loading={true} size={32} />
Ditto here - is the new color what's in the Figma? These are the things that Vanessa should review - is the new usage of the changed color OK?

2023-04-27 17:43 UTC, hankewyczz commented on generated/graphql.ts
> +  totalCount: Scalars['Int'];
This shouldn't be in your PR — run `git checkout origin/master -- generated/graphql.ts`

2023-04-27 17:43 UTC, hankewyczz commented on styles/_CheckboxFilter.scss
> -      background-color: #eaeaea;
Same here - I won't leave a comment in every spot, but these are the kinds of design changes that need to be reviewed. Going from `#FFFFFF` to `white` doesn't matter - going from a different color to white does matter

2023-04-30 21:44 UTC, sebwittr approved these changes
There was one place that Zachar mentioned where a variable wasn't being used, but other than that everything looks good!

2023-04-30 21:53 UTC, Lucas-Dunker commented on components/ResultsPage/FeedbackModal/FeedbackModal.tsx
> -          <LogoInput height="14" width="18" fill="#d41b2c" />
I decided not to use color variables for SVGs and their corresponding tsx files, especially for fill attributes; I didn't think it made much semantic sense to make them variables since lots of them were likely imported straight from figma and they're more closely related to the actual shapes/components themselves than to styling (plus, there are lots of them). Let me know if this makes sense! If it doesn't, I can definitely go in and abstract them to variables

2023-05-01 00:08 UTC, Lucas-Dunker commented on components/common/AlertBanner.tsx
> -            <IconClose fill="#808080" />
1. Whoops! Thanks for the catch
2. Yep, a big part of this ticket was standardizing the colors to our palette on the figma, so some of the colors changed slightly; this is intentional!

2023-05-01 00:09 UTC, Lucas-Dunker commented on components/icons/Husky.tsx
> -          fill="#fff"
that mightve been a strange autoformatter thing, ill go back and fix that

2023-05-01 00:09 UTC, Lucas-Dunker commented on components/notifications/modal/SignUpModal.tsx
> -            <MoonLoader color={'#7fc4c7'} loading={true} size={32} />
Yep, thats the new figma color, waiting for vanessa's feedback!

2023-05-01 00:10 UTC, Lucas-Dunker commented on styles/_CheckboxFilter.scss
> -      background-color: #eaeaea;
Agreed; I'll switch @vanessa-peng from a secondary reviewer to a primary one.

2023-05-01 16:39 UTC, hankewyczz commented on components/ResultsPage/FeedbackModal/FeedbackModal.tsx
> -          <LogoInput height="14" width="18" fill="#d41b2c" />
I think this would be a good spot to use the color variables. In static content (like the SVGs themselves), you're right; there's no point in using variables there, since those are directly exported from Figma. 

However, in a spot like this, where the content is actually being used (in a variable setting), we should use the color variables. (ig a simpler way of explaining it is that if a dev wouldn't ever actually type this, the hex code is OK. If a dev would write this, use the variables)

2023-05-10 01:10 UTC, Lucas-Dunker commented
Vanessa has approved the color changes!

2023-05-10 20:36 UTC, hankewyczz requested changes
This looks great! I just have one suggestion — we need a way of enforcing this. New devs will onboard not knowing about this, and we should have guardrails (like the Github tests) to tell them that's not the right way of doing things. 

We can use the [`no-restricted-syntax`](https://eslint.org/docs/latest/rules/no-restricted-syntax)
rule in ESLint to ensure that our linter catches bad uses of hex codes. 

For our uses, something like this should work:
```js
"no-restricted-syntax": [
      "error",
      { "selector": "Literal[value=/^#[a-zA-Z0-9]/i]", "message": "Use 'Colors' from '<location>'" },
      { "selector": "Literal[value=/^rgb[(]/i]", "message": "Use 'Colors' from '<location>'" },
      { "selector": "Literal[value=/^rgba[(]/i]", "message": "Use 'Colors' from '<location>'" }
    ]
```

That rule will create a linter error every time someone tries using a hex code, RGB, or RGBA. It won't cover the case where someone uses a literal color (eg. `color: red`), but that's better than nothing!

You can disable this rule using [ESLint comments](https://eslint.org/docs/latest/use/configure/rules#disabling-rules) to exclude specific sections (like the SVG files).

2023-05-11 03:30 UTC, Lucas-Dunker commented
> This looks great! I just have one suggestion — we need a way of enforcing this. New devs will onboard not knowing about this, and we should have guardrails (like the Github tests) to tell them that's not the right way of doing things.
> 
> We can use the [`no-restricted-syntax`](https://eslint.org/docs/latest/rules/no-restricted-syntax) rule in ESLint to ensure that our linter catches bad uses of hex codes.
> 
> For our uses, something like this should work:
> 
> ```js
> "no-restricted-syntax": [
>       "error",
>       { "selector": "Literal[value=/^#[a-zA-Z0-9]/i]", "message": "Use 'Colors' from '<location>'" },
>       { "selector": "Literal[value=/^rgb[(]/i]", "message": "Use 'Colors' from '<location>'" },
>       { "selector": "Literal[value=/^rgba[(]/i]", "message": "Use 'Colors' from '<location>'" }
>     ]
> ```
> 
> That rule will create a linter error every time someone tries using a hex code, RGB, or RGBA. It won't cover the case where someone uses a literal color (eg. `color: red`), but that's better than nothing!
> 
> You can disable this rule using [ESLint comments](https://eslint.org/docs/latest/use/configure/rules#disabling-rules) to exclude specific sections (like the SVG files).

Agreed! I'll do this in a new PR for organization.

2023-05-11 17:12 UTC, hankewyczz approved these changes

2023-05-11 17:19 UTC, merged