Add linting rules to error on hex codes (instead of color variables)
sandboxnu/searchneu-v1 pull request #212
Opened 2023-05-23 21:29 UTC by Lucas-Dunker

# Purpose

Now that all of the dev-edited hex codes have been replaced with color variables, we should probably have some sort of linting rule that enforced them (as per @hankewyczz 's suggestion). This PR adds exactly that!

# Tickets

No associated trello ticket lol
![image](https://github.com/sandboxnu/searchneu/assets/93111430/ac08f4fa-0077-4017-9460-bc734985bd06)

# Contributors

@Lucas-Dunker 

# Feature List

-Linting rule for using raw hex codes
-Some additional comments for using color hex codes in development

# Reviewers

**Primary**:
@hankewyczz @sebwit20 

**Secondary**:
@pranavphadke1 @soulwa

2023-05-24 14:07 UTC, hankewyczz requested changes
Looks great! One big thing - could you break out the Node upgrade into a separate PR? It's easier to track/review that way (there's some parts of the codebase that need to also be upgraded [off the top of my head, `.nvmrc`])

2023-05-24 14:07 UTC, hankewyczz commented on .eslintrc.json
> +    "no-restricted-syntax": [
[nit] could you add some more detail into the message (or add a comment, but I'd prefer the former so they don't have to go looking for it)? Imagine you're a new developer who expects hex codes to work as usual - what's important for them to know?

2023-05-24 14:07 UTC, hankewyczz commented on package.json
> +    "postcss": "8",
```suggestion
    "postcss": "^8",
```

2023-05-24 14:07 UTC, hankewyczz commented on pages/_document.tsx
> +/* eslint-disable no-restricted-syntax */
I think this is a good spot to use the variable instead of ignoring the lint rule

2023-05-24 15:25 UTC, Lucas-Dunker commented on pages/_document.tsx
> +/* eslint-disable no-restricted-syntax */
Unfortunately document.tsx doesn't allow css, I tried for the last pr but the project wouldn't compile

2023-05-24 15:26 UTC, Lucas-Dunker commented on .eslintrc.json
> +    "no-restricted-syntax": [
Totally!

2023-05-24 15:28 UTC, Lucas-Dunker commented
> Looks great! One big thing - could you break out the Node upgrade into a separate PR? It's easier to track/review that way (there's some parts of the codebase that need to also be upgraded [off the top of my head, `.nvmrc`])

I can definitely do that, but that PR will have to be approved first for this PR to work!

2023-05-24 15:38 UTC, hankewyczz commented
> I can definitely do that, but that PR will have to be approved first for this PR to work!

Yep, that's fine - I typically had a few PRs up like that at any given time. While you're working on the new branch (let's call it `node-upgrade` for this), you can just `pull origin/node-upgrade` into this branch. That'll ensure that this branch still works as intended.

I'd recommend adding `[DRAFT]` to the title of this PR until the node upgrade PR is merged

2023-10-01 19:00 UTC, sebwittr approved these changes
I think this is a good lint rule, just make sure to add a description to the rule so it's obvious why it's erroring.

2023-10-01 20:53 UTC, hankewyczz reviewed
comment

2023-10-01 20:54 UTC, hankewyczz approved these changes

2023-10-02 00:06 UTC, merged