Add ctrl+click to the "View more info for this class" button, remove "back to search results" url.
sandboxnu/searchneu-v1 pull request #238
Opened 2024-01-22 05:23 UTC by Lucas-Dunker

# Purpose

This ticket turns the "View more info for this class' button into a url, allowing it to be more easily copied and ctrl-clicked. In the process, I found a bug related to graphql making queries before all the react data is loaded; a conditional has been added to wait for the necessary data to load before any data is fetched.

I also decided to remove the "back to search results" url, since I felt that it was unnecessary - other search engines like YouTube and Google don't have back buttons on their sites, they just rely on the browser. I can definitely roll this back if you think it's better to have it!

Feel free to check out the vercel deployment and see this change for yourself! 

# Tickets

[This ticket!](https://trello.com/c/pk772KOj/342-allow-ctrlclicking-of-class-pages)

# Contributors

@Lucas-Dunker 

# Pictures
![image](https://github.com/sandboxnu/searchneu/assets/93111430/69bf6288-059a-4462-9461-73285df92c0e)

![image](https://github.com/sandboxnu/searchneu/assets/93111430/988fe9b6-386b-4b4e-beaf-3f6b7a4e4657)

# Reviewers

**Primary**:
@pranavphadke1 

**Secondary**:
@sebwittr @ananyaspatil

2024-02-03 04:43 UTC, pranavphadke1 approved these changes
goat

2024-02-15 20:02 UTC, sebwittr requested changes
Thanks for making this! Just had one minor thing, but everything looks good.

2024-02-15 20:02 UTC, sebwittr commented on components/ResultsPage/Results/CourseResult.tsx
> +                <a
We should probably use <Link> instead of an <a> tag, since it works with the React router and gives us this functionality still. I think with Next it also prerenders the pages that are being linked, so theres little to no waiting.

2024-02-15 20:02 UTC, sebwittr commented on pages/[campus]/[termId]/classPage/[subject]/[classId].tsx
> +  }, [subject, classId, router]);
Is router required here as a dependency?

2024-02-15 20:06 UTC, Lucas-Dunker commented on components/ResultsPage/Results/CourseResult.tsx
> +                <a
Sorry, what should we use instead? If you’re referring to a `Link` tag, unfortunately that doesn’t allow ctrl clicking.

2024-02-15 20:06 UTC, Lucas-Dunker commented on pages/[campus]/[termId]/classPage/[subject]/[classId].tsx
> +  }, [subject, classId, router]);
Yes, we get graphql errors otherwise.

2024-02-19 22:14 UTC, sebwittr commented on components/ResultsPage/Results/CourseResult.tsx
> +                <a
oops yea I was talking about Link. Apparently someone had a similar issue (https://github.com/vercel/next.js/issues/7218), and the solution was to just put the href in the Link tag. If that doesn't work I'd be ok with the plain a tag.

2025-11-03 23:25 UTC, closed without merging