Initial Subscription page skeleton
sandboxnu/searchneu-v1 pull request #248
Opened 2024-02-03 01:33 UTC by pranavphadke1

# Purpose
This is the initial skeleton code for developing the subscription page.

# Tickets

- https://trello.com/c/DnjL1887

# Contributors

@pranavphadke1 @sebwittr @allychao 

# Feature List

- Displays all subscribed courses and sections at 'http://localhost:5000/subscriptions'
- Also displays sections that users haven't subscribed to but can (sections with less than 5 seats remaining)
- Can toggle to subscribe or unsubscribe from a section
- Added a link under the user icon that takes you to the subscription page (code commented out until page is finalized)

# To Do 
- Unsubscribe button on top right of class card doesn't do anything yet
- Need to add the header bar
- Make the class cards collapse to hide section info
- Additional styling

# Pictures
![image](https://github.com/sandboxnu/searchneu/assets/91645231/6128c82d-9f4d-49a0-a0aa-b2b910f9eb6d)

# Reviewers

**Primary**:
@sebwittr @soulwa 

**Secondary**:
@ananyaspatil @Anzhuo-W 
@Lucas-Dunker if you wanna :D

2024-02-03 01:46 UTC, pranavphadke1 commented on components/Header.tsx
> +                  {/* <span className="user-menu__item" onClick={subscriptionPage}>
This is commented out until the page is finalized

2024-02-03 01:47 UTC, pranavphadke1 commented on components/ResultsPage/ResultsLoader.tsx
> +      // I ran into some cases where dayIndex isn't an array causing the foreach to break below.
Some bug I saw that might be fixed. Just leaving this here incase the same issue occurs in later development.

2024-02-03 01:49 UTC, pranavphadke1 commented on pages/subscriptions.tsx
> +  const [userInfo, isLoading, fetchUserInfo] = useUserInfo();
On a userInfo object, we store what courses and sections a user is subscribed to with list of courseIds and sectionIds. For this subscription page to work, we need to use these ids to find the associated courses and list the sections one can/have subscribed to as well.

2024-02-03 01:50 UTC, pranavphadke1 commented on pages/subscriptions.tsx
> +    const fetchCourseNotifs = async (): Promise<void> => {
This function looks through userInfo.courseIds to find courses that a user might be subscribed to.

2024-02-03 01:52 UTC, pranavphadke1 commented on pages/subscriptions.tsx
> +    const fetchSectionNotifs = async (): Promise<void> => {
This function looks through userInfo.sectionIds to find their associated courses. If those courses were not found by the function above (fetchCourseNotifs), it will add the new course to the list of classes

2024-02-15 19:24 UTC, sebwittr requested changes
Left some comments about cleaning up the code, and I had some questions. It is looking really good though.

2024-02-15 19:24 UTC, sebwittr commented on components/Header.tsx
> +  const subscriptionPage = (): void => {
Probably should comment this out to appease the linter

2024-02-15 19:24 UTC, sebwittr commented on pages/subscriptions.tsx
> +  const [userInfo, isLoading, fetchUserInfo] = useUserInfo();
can we rename isLoading to isUserInfoLoading or something similar? It makes it a little more clear

2024-02-15 19:24 UTC, sebwittr commented on pages/subscriptions.tsx
> +            return s.seatsRemaining <= 5;
We filter the sections to only keep the ones who have <= 5 seats remaining, since those are the ones you can sign up for notifs.

2024-02-15 19:24 UTC, sebwittr commented on pages/subscriptions.tsx
> +              campusDescription: '',
remove campusDescription from here and types.ts since its not used anywhere

2024-02-15 19:24 UTC, sebwittr commented on components/SubscriptionsPage/ClassCard.tsx
> +            prettyUrl={''} //Ignore this for now, the current link we use is outdated anyway. Will need to be course.prettyUrl
This might be useless after the ticket removing the link from the class card

2024-02-15 19:24 UTC, sebwittr commented on components/ResultsPage/ResultsLoader.tsx
> +      if (!Array.isArray(times[dayIndex])) {
if times[dayIndex] isn't an array what actually is it, and what happens on the actual site?

2024-02-15 19:24 UTC, sebwittr commented on components/SubscriptionsPage/ClassCard.tsx
> +import { ReactElement } from 'react';
How much of this is the same as the class card from Search results, and what here is different? We might want to name this component something like SubscriptionClassCard to make it more specific.

2024-02-15 19:24 UTC, sebwittr commented on pages/subscriptions.tsx
> +          const courseResult = await gqlClient.getCourseInfoByHash({
This is repeated logic from the other course function, can we generalize it in another function so we don't have duplicate code.

2024-02-15 20:30 UTC, pranavphadke1 commented on components/ResultsPage/ResultsLoader.tsx
> +      if (!Array.isArray(times[dayIndex])) {
times[dayindex] should be the format [obj,obj, ...] but for some reason there are instances where it is just a single obj, without being wrapped by a list. I'm not too sure why this happens as the flow to get all this logic is the exact same as the results loader (which doesn't have the issue). For now let's leave this filter check in and look into finding the root cause before we push the final changes for the page

2024-02-15 23:09 UTC, soulwa commented on components/types.ts
> +
is there a need for this type? it doesn't seem to be used anywhere and seems to just pollute the types more since it only differs by one field from `Section`, so it seems we could just use a `Section` when we want to return/receive a `SubscriptionSection`.

2024-02-15 23:09 UTC, soulwa commented on components/SubscriptionsPage/ClassCard.tsx
> +import { ReactElement } from 'react';
+1, I think it might be worth looking at what you can offload from this component onto the search result. in particular we don't really need the `ClassCardWrapperType` and `ClassCardWrapper` - those are the exact same as `SearchResultProps` and `SearchResult`. ultimately I'm not too hung up on this though, seems to make sense and works

2024-02-15 23:09 UTC, soulwa commented on pages/subscriptions.tsx
> +  const [userInfo, isLoading, fetchUserInfo] = useUserInfo();
+1

2024-02-15 23:09 UTC, soulwa commented on components/SubscriptionsPage/ClassCard.tsx
> +      headerRight={<button>Unsubscribe</button>}
unsubscribe functionality isn't working (yet), but it might be worth clarifying what this is intended to do. should it unsubscribe the user from all sections, and the course? or should it just unsubscribe from the course? currently, there's no visual on this component which indicates that you are subscribed to a course and not a section (like there is in the results page), which gives the user weird situations where it maybe seems like they should be unsubscribed, eg.

<img width="1735" alt="Screenshot 2024-02-15 at 18 07 44" src="https://github.com/sandboxnu/searchneu/assets/20330404/0ea20311-18fa-4e51-aba3-d36251f71d57">

2024-02-15 23:09 UTC, soulwa commented on pages/subscriptions.tsx
> +          const courseResult = await gqlClient.getCourseInfoByHash({
+1

2024-02-19 23:09 UTC, pranavphadke1 commented on components/SubscriptionsPage/ClassCard.tsx
> +import { ReactElement } from 'react';
I agree. I plan on abstracting all of this later once more works has been merged into this page since we already have branches working off this right now.

2024-02-20 23:42 UTC, merged