Subject Descriptions in Subject Filter
sandboxnu/searchneu-v1 pull request #25
Opened 2020-12-01 03:43 UTC by megandouli

# what
Want the longer subject description (ex: Computer Science) in addition to the subject abbreviation (ex: CS) in the subject filter

# how
Added a subjects table to the database
Added an optional description property to relevant types
Changed the CSS styling so description shows up on a separate line

2020-12-02 05:53 UTC, epillay approved these changes
amazing stuff on the frontend :meow-wow:

2020-12-02 07:04 UTC, puneetjohal approved these changes
Looks and works great! Thanks for picking up this ticket Megan :)

2020-12-02 07:08 UTC, beccajohnson17 approved these changes
this is a 10000x increase in the usability of the subject filter.

2020-12-03 01:44 UTC, gamburgm requested changes
We should add :chungus: to GitHub reacts :beyes:

2020-12-03 01:44 UTC, gamburgm commented on frontend/components/ResultsPage/filters.ts
>    count: number
can you add a comma here :^)

2020-12-03 01:44 UTC, gamburgm commented on backend/scrapers/classes/parsersxe/subjectAbbreviationParser.js
> +export { createDescriptionTable as _createDescriptionTable }
Can you add a semicolon here?

2020-12-03 01:44 UTC, gamburgm commented on backend/searcher.ts
> +  getSubjects(): {} {
Can you change this to the same name as the type of the `subjects` property?

2020-12-03 01:44 UTC, gamburgm commented on backend/searcher.ts
> +        return [filter, results[idx + 1].aggregations[filter].buckets.map((aggVal) => {
Can we re-format this for clarity? e.g.
```
return [
    filter,
    results[idx + 1].aggregations[filter].buckets.map((aggVal) => {
...
];
```

Honestly, might make sense to break the aggregations generation into a helper function that we invoke in the map.

2020-12-03 02:44 UTC, gamburgm approved these changes
Bet :+1:

2020-12-03 02:45 UTC, merged