Ap/no notifications husky page
sandboxnu/searchneu-v1 pull request #265
Opened 2024-04-14 05:57 UTC by ananyaspatil

# Purpose
Creates an EmptyCard to display for the Empty Notifications page. 
When "Search for classes" button is hovered over, crying-husky image changes to happy-husky image. 
Includes a placeholder text for "Spring 2023 Notifications", this will need to be changed to actually reflect the semester of notifications being displayed.

# Tickets
https://trello.com/c/SoJpDQFG

-

# Contributors

@ananyaspatil @Anzhuo-W 

# Feature List
Created display for the Empty Notifications page. 
 - Created EmptyCard Component: contains display text and a button that redirects to the default search page
 - added crying-husky.svg and happy-husky.svg images
When "Search for classes" button is hovered over, crying-husky image changes to happy-husky image. 
 - Added isHovering const to EmptyCard
 - Added logic to update husky image to happy when OnMouseEnter is true for "search for classes" button
Includes a placeholder text for "Spring 2023 Notifications", this will need to be changed to actually reflect the semester of notifications being displayed.

# Pictures
No Hover:
<img width="1434" alt="image" src="https://github.com/sandboxnu/searchneu/assets/106994008/c811e487-ba0d-4b80-bc9a-83001f187051">

Hover:
<img width="1434" alt="image" src="https://github.com/sandboxnu/searchneu/assets/106994008/6c3b5e4e-c047-4be4-bcf0-3723841420d3">

# Reviewers

Primary reviewer:
@pranavphadke1 @sebwittr 

Secondary reviewers:
@soulwa

2024-04-14 06:00 UTC, ananyaspatil commented on components/SubscriptionsPage/EmptyCard.tsx
> +                    onMouseEnter={() => setIsHovering(true)}
To change image upon hovering, am setting isHovering constant to true when mouse enters the Button and to false when mouse leaves the button.

2024-04-14 06:00 UTC, ananyaspatil commented on components/SubscriptionsPage/EmptyCard.tsx
> +  const [isHovering, setIsHovering] = useState(false);
Added const isHovering so that Husky image can be changed when mouse hovers over the "search for classes" button

2024-04-14 06:02 UTC, ananyaspatil commented on pages/subscriptions.tsx
> +        // are there classes the user is subscribed to?
Adding condition for when to display the No Notifications page

2024-04-14 16:17 UTC, sebwittr requested changes
This looks good, main thing is the changes to ClassCardWrapper. I think we shouldn't need to touch that file at all, since it's only supposed to wrap actual class cards. The EmptyCard should serve as its own component, and not really need to rely on that.

2024-04-14 16:17 UTC, sebwittr commented on components/SubscriptionsPage/ClassCard.tsx
> +      <div>{headerLeft}</div>
I think we needed the styles from SearchResult__header and SearchResult__header--left for the class cards. Did your changes actually need to change this file?

2024-04-14 16:17 UTC, sebwittr commented on components/SubscriptionsPage/EmptyCard.tsx
> +      <div className="Results_Container">
We probably don't need all these extra styles, and it would be better to make a separate style sheet for EmptyCards.

2024-04-14 16:17 UTC, sebwittr commented on styles/pages/_Results.scss
> +    .SearchResult {
I would move these out into a separate _EmptyCard.scss so we don't put too much into this file.

2024-11-17 21:52 UTC, Anzhuo-W commented
Trello ticket

<img width="766" alt="Screen Shot 2024-11-17 at 4 51 17 PM" src="https://github.com/user-attachments/assets/a683e755-d019-4452-bffb-e5d5b4e7fc7c">

2024-11-21 17:34 UTC, cherman23 commented
Styles have been moved to new EmptyStyles, Empty Card automatically updates to show current semester.

2024-11-22 14:37 UTC, mehallhm reviewed
Generally looks pretty good, just some comments on code consistency and readability for the rest of the codebase

2024-11-22 14:37 UTC, mehallhm commented on components/SubscriptionsPage/ClassCard.tsx
> +export const ClassCardWrapper = ({
Let's match the rest of the codebase here and use `function` definitions rather than arrow notations. It seems to be like a 70 / 30 split on what we do, but we should pick one to stick with, and I'll just go with the majority

2024-11-22 14:37 UTC, mehallhm commented on package.json
> +    "leading-trim": "^1.0.2",
I would like to see evidence that adding a package is the correct call here. It's fine if we actually need it, but I would like that proof

2024-11-22 14:37 UTC, mehallhm commented on pages/subscriptions.tsx
> +          setIsSubscribed(true);
Why is a state variable being reassigned to another state variable? I would just use `classMapping.size > 0` instead of managing a derived piece of state

2024-11-22 14:37 UTC, mehallhm commented on pages/subscriptions.tsx
>        {isFetching ? (
I don't love the ternary, especially nested ones. Would an early return be better? This is really not that important but just thinking from a readability standpoint.

2024-11-24 21:26 UTC, cherman23 commented on pages/subscriptions.tsx
> +          setIsSubscribed(true);
we will address this in a future ticket

2024-11-24 21:26 UTC, cherman23 commented on package.json
> +    "leading-trim": "^1.0.2",
addressed in recent commit

2024-11-24 21:26 UTC, cherman23 commented on components/SubscriptionsPage/ClassCard.tsx
> +export const ClassCardWrapper = ({
addressed in recent commit

2024-11-24 21:26 UTC, cherman23 commented on pages/subscriptions.tsx
>        {isFetching ? (
we will address this in a future ticket

2024-12-04 22:48 UTC, merged