Adjust bugs on notification page.
sandboxnu/searchneu-v1 pull request #304
Opened 2024-12-17 00:43 UTC by cherman23

# Purpose

Empty card was not displaying properly, fixed padding on styling. Create new modal to inform users of notifications page. Reinstate @mehallhm unsubscribe functionality.

# Ticket

no ticket.

# Reviewers

Primary reviewer:

@ananyaspatil 

Secondary reviewers:

@nickpfeiffer05 
@Anzhuo-W 
@mehallhm

2025-01-19 22:01 UTC, nickpfeiffer05 commented
Does NewSubscriptionsLimitModal have any use cases now?

2025-01-23 17:37 UTC, mehallhm requested changes
Notes:
- The Hooky add classes button redirects to the search page with an undefined term code
- Sign out button still clips off the page
- Are the dots with the CRN supposed to change color (ie if notifications are enabled for that section?)
- Prob should get rid of the modal

2025-01-24 17:48 UTC, cherman23 commented
I pushed a commit that addresses some of micheals comments (listed in commit message).

Currently trying to get my dev instance to allow me to sign up for classes so I can  see the class cards on the subscriptions page.

2025-02-02 20:37 UTC, mehallhm approved these changes

2025-02-02 21:06 UTC, merged