dc/graphql search
sandboxnu/searchneu-v1 pull request #42
Opened 2020-12-13 19:08 UTC by dajinchu

2020-12-21 05:01 UTC, gamburgm requested changes
Looks pretty good but added some comments. Also, the type errors in `updater.test.seq.ts` I think are caused by this PR (we'll get rid of the `dumpProcessor` type errors in the re-write). 

What's the plan for typescript GraphQL?

2020-12-21 05:01 UTC, gamburgm commented on backend/graphql/index.js
> +  type PageInfo {
Don't we only have this property on the search endpoint (and if so, shouldn't this just be a property there)?

2020-12-21 05:01 UTC, gamburgm commented on backend/graphql/resolvers/search.ts
> +type SearchResultItem = Course | Employee;
Nit: `SearchResult` vs. `SearchResultItem`, `SearchResultMeta` vs. `SearchResultItemConnection`? I care less about the former than the latter, I don't think `connection` accurately describes the data here

2020-12-21 05:01 UTC, gamburgm commented on backend/graphql/resolvers/search.ts
> +    search: async (
Nit but can you put the function declaration on one line?

2020-12-21 05:01 UTC, gamburgm commented on backend/graphql/resolvers/search.ts
> +  first: number;
What is `first` supposed to mean? Is this supposed to be like `first ten` kinda thing? If so, then I think `count` or `size` would be better

2020-12-21 05:01 UTC, gamburgm commented on backend/graphql/resolvers/search.ts
> +      const results = await searcher.search(
In theory you could destructure here for `resultCount` and `searchContent`, but no big deal either way.

2020-12-21 05:01 UTC, gamburgm commented on backend/graphql/typeDefs/classOccurrence.js
> +    classAttributes: [String!]!
I think it's possible for `classAttributes` to be empty, how would you express that?

2020-12-21 05:01 UTC, gamburgm commented on backend/search_types.ts
> +export type SearchResult =
This is not directly related to this ticket but should we change the model to not have these `type` declarations?

2020-12-23 23:16 UTC, dajinchu commented on backend/graphql/index.js
> +  type PageInfo {
It's just a GraphQL standard for pagination. We will likely need it in many places.

2020-12-23 23:19 UTC, dajinchu commented on backend/graphql/resolvers/search.ts
> +  first: number;
https://graphql.org/learn/pagination/#pagination-and-edges Just GraphQL standard.

2020-12-23 23:20 UTC, dajinchu commented on backend/graphql/resolvers/search.ts
> +type SearchResultItem = Course | Employee;
GraphQL convention uses Item and Connection. Some graphql clients like Relay require it to be in this format to auto-handle pagination. 

For example: https://docs.github.com/en/free-pro-team@latest/graphql/reference/queries#searchresultitemconnection

2020-12-23 23:22 UTC, dajinchu commented on backend/graphql/typeDefs/classOccurrence.js
> +    classAttributes: [String!]!
Empty is allowed by this type def. `[Type]!` means it must be an array and not null. `[Type!]` means the items must be of Type and not null.
`[]` is an array with items that are not null.

2020-12-27 03:44 UTC, NEUDitao approved these changes

2020-12-29 00:58 UTC, gamburgm approved these changes
:+1:

2020-12-29 00:59 UTC, merged