[WIP] Remove class models
sandboxnu/searchneu-v1 pull request #54
Opened 2020-12-27 18:42 UTC by ArunJ98

2020-12-27 18:49 UTC, ArunJ98 commented on frontend/components/ResultsPage/Results/SearchResult.tsx
> +export function MobileSearchResult({ aClass } : SearchResultProps) {
Added MobileSearchResult to same file so we can use common helper functions

2020-12-27 18:49 UTC, ArunJ98 commented on frontend/components/ResultsPage/Results/SectionPanel.tsx
> +import React from 'react';
This file is just DesktopSectionPanel and MobileSectionPanel combined so we can use common helper functions without a utils file.

2020-12-27 18:49 UTC, ArunJ98 commented on frontend/components/ResultsPage/Results/useResultDetail.tsx
> +    const isCompositeReq = (variableToCheck: any): variableToCheck is CompositeReq =>
Type guard helpers

2020-12-27 18:49 UTC, ArunJ98 commented on frontend/components/ResultsPage/Results/useResultDetail.tsx
> +    childNodes.forEach((childBranch) => {
The functionality here hasn't changed, just refactored to use Requisite type instead of Course class

2020-12-27 18:49 UTC, ArunJ98 commented on frontend/components/ResultsPage/ResultsLoader.tsx
> +function getFormattedsections(sections: any): Section[] {
we're reformatting sections to match our interface for meetings

2020-12-27 18:49 UTC, ArunJ98 commented on frontend/components/classModels/_Meeting.ts
>            }
we can ignore these files starting with '_', will be deleted soon

2020-12-27 18:49 UTC, ArunJ98 commented on frontend/components/types.ts
> +export interface Course {
This is the core of the refactor, we've replaced the class models with the types here

2020-12-27 19:48 UTC, megandouli requested changes

2020-12-27 19:48 UTC, megandouli commented on frontend/components/ResultsPage/Results/useResultDetail.tsx
> +        console.log("asdfaskdfh")
Take this log out?

2020-12-27 19:48 UTC, megandouli commented on frontend/components/ResultsPage/Results/useResultDetail.tsx
> +          retVal.push(['(', getReqsStringHelper(course, PrereqType.PREREQ, childBranch.values), ')']);
not sure where the bug is but when I pulled this branch and searched for cs4500, I got 
`CS 3500 and (ENGW 1111 and ENGW 1102)`
as the prereqs and it should be 
`CS 3500 and (ENGW 1111 or ENGW 1102)`

2020-12-27 20:21 UTC, NEUDitao reviewed
small nits but looks great so far :o

2020-12-27 20:21 UTC, NEUDitao commented on frontend/components/ResultsPage/Results/SearchResult.tsx
> +export function SearchResult({ aClass } : SearchResultProps) {
can we just like, make this `course`? `aClass` is *so* 2017

2020-12-27 20:21 UTC, NEUDitao commented on frontend/components/ResultsPage/ResultsLoader.tsx
> +function getFormattedsections(sections: any): Section[] {
`getFormattedSections` ?

2020-12-27 20:21 UTC, NEUDitao commented on frontend/components/ResultsPage/ResultsLoader.tsx
> +    const dayIndexies = Object.keys(times);
lol indices?

2020-12-27 20:22 UTC, megandouli commented on frontend/components/ResultsPage/Results/useResultDetail.tsx
> +          retVal.push(['(', getReqsStringHelper(course, PrereqType.PREREQ, childBranch.values), ')']);
I messed around locally and I think the problem is in this chunk of code (lines 139 - 143)
`      if (reqType === PrereqType.PREREQ) {
        type = course.prereqs.type;
      } else if (reqType === PrereqType.COREQ) {
        type = course.coreqs.type;
      }`

The course prereqs/coreqs type is always the same because we recursively pass in the same course on lines 121 and 123 to `getReqsStringHelper.` We could pass in `childBranch` on those lines instead and do 
`      if (reqType === PrereqType.PREREQ) {
        type = course.type || course.prereqs.type;
      } else if (reqType === PrereqType.COREQ) {
        type = course.type || course.coreqs.type;
      }`

2020-12-27 20:53 UTC, ArunJ98 commented on frontend/components/ResultsPage/ResultsLoader.tsx
> +    const dayIndexies = Object.keys(times);
lol this is copy pasted from class models

2020-12-27 21:15 UTC, dajinchu approved these changes

2020-12-28 17:14 UTC, megandouli approved these changes
Awesome!

2020-12-29 02:04 UTC, dajinchu approved these changes

2020-12-29 02:12 UTC, megandouli reviewed
Looks good!

2020-12-29 02:18 UTC, gamburgm reviewed
Some comments

2020-12-29 02:18 UTC, gamburgm commented on backend/scrapers/classes/parsersxe/bannerv9Parser.js
> +  async main() {
Can you add it back and just add a `macros.log(termsUrl)` in the function instead?

2020-12-29 02:18 UTC, gamburgm commented on frontend/components/ResultsPage/Results/SearchResult.tsx
> +export function MobileSearchResult({ course } : SearchResultProps) {
Is there a concern that this file is too long with the added component or nah/what's the design idea here

2020-12-29 02:18 UTC, gamburgm commented on backend/types.ts
> +export function isBooleanReq(req: Requisite): req is CompositeReq {
Should be `isCompositeReq`

2020-12-29 02:18 UTC, gamburgm commented on frontend/components/ResultsPage/Results/useResultDetail.tsx
> +    const isCompositeReq = (variableToCheck: any): variableToCheck is CompositeReq => (variableToCheck as CompositeReq).type !== undefined;
This function exists in `backend/types`, you should probably move that to `common/types` and import that function. In theory if you really wanted to you could create a `req_type.ts` file but that's probably not a good idea.

2020-12-29 08:00 UTC, NEUDitao commented on frontend/components/ResultsPage/Results/useResultDetail.tsx
> +    const isCompositeReq = (variableToCheck: any): variableToCheck is CompositeReq => (variableToCheck as CompositeReq).type !== undefined;
I think keeping it here is fine... considering that the backend is about to get yeeted int outer space

2020-12-29 08:00 UTC, NEUDitao approved these changes

2020-12-29 16:26 UTC, ArunJ98 commented on backend/scrapers/classes/parsersxe/bannerv9Parser.js
> +  async main() {
yessir

2020-12-29 16:27 UTC, ArunJ98 commented on frontend/components/ResultsPage/Results/SearchResult.tsx
> +export function MobileSearchResult({ course } : SearchResultProps) {
Not too concerned about the file length. Wanted to keep all helper functions localized to this file and since both Desktop and Mobile have common helpers, I combined them.

2020-12-29 16:27 UTC, ArunJ98 commented on backend/types.ts
> +export function isBooleanReq(req: Requisite): req is CompositeReq {
good catch, thanks!

2020-12-29 16:29 UTC, ArunJ98 commented on frontend/components/ResultsPage/Results/useResultDetail.tsx
> +    const isCompositeReq = (variableToCheck: any): variableToCheck is CompositeReq => (variableToCheck as CompositeReq).type !== undefined;
maybe we move it to a common library but we gotta figure out the solution for that first. I think for now, it's ok to leave it here.

2020-12-29 21:41 UTC, merged