Ad 404 page
sandboxnu/searchneu-v1 pull request #90
Opened 2021-03-08 15:46 UTC by andrewydai

2 things to worry about:
- Naming convention (I usede four04 for variables that can't start with number)
- Is using the next library the correct way to reroute to homepage?

2021-03-08 16:39 UTC, dajinchu requested changes
looks great. just delete `package-lock.json` and use `yarn` to install dependencies instead of `npm`

2021-03-08 16:39 UTC, dajinchu commented on utils/courseAPIClient.ts
> +const ENDPOINT = 'http://localhost:4000';
Just change this back and clean up the big comment block below

2021-03-09 01:22 UTC, andrewydai commented on utils/courseAPIClient.ts
> +const ENDPOINT = 'http://localhost:4000';
Thanks! Yeah I think I was just on auto pilot and added some file changes I didn't mean to.

2021-03-17 00:22 UTC, NEUDitao approved these changes

2021-04-05 14:37 UTC, NEUDitao commented
can we get this bumped? as much as I love `404: YOU GOT LIGMA!` it'd be cool to see Diana's work in prod

2021-04-05 21:54 UTC, dajinchu approved these changes

2021-04-05 23:08 UTC, merged